### ISSUE TITLE
Version check when looking up mods

### ISSUE THREAD

**Issue by ColonelGerdauf** [PrismLauncher/PrismLauncher#1044]
### Operating System

Windows, Linux

### Version of Prism Launcher

Prism 6.3

### Version of Qt

QT 6.3

### Description of bug

A number of mods struggle to correctly load up the version information on first look, displaying a "no valid version found". This is despite the fact that a valid version does exist, and often requires users to click on a random other mod, and click back to where they were in order to see the correct number, and therefore be able to download it.

### Steps to reproduce

this is very sporadic, and it is hard to come with a distinct example to draw steps from

* open prism
* load instance editor
* go to mods
* click "download mods"
* type anything, basically
* on either Modrinth or CurseForge, look through the mods
* somewhere, you will run into the issue, assuming that the mod isn't somehow for a different platform (why is this a thing?)

### Suspected cause

from Discord discussions, it appears that a contributing factor is the third party block on CurseForge. That is unfortunate and also not the total cause.

First, the third party blocking is a new mechanism within CF, and many modders, especially the newer/inexperienced/fly-by's do not bother to switch for the setting where the blocking is default. I personally doubt that many modders are even aware of this mechanism, for many reasons.

Second, that is exclusive to CF. This issue also happens in Modrinth. Not to mention, this bug shows up sporadically and sparingly.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by UcraNerd** [comment]
The funny thing is that you can still update already instaled modpacks fro Modrinth

**Comment by Trial97** [comment]
Ok so mostly found the issue:
- Modrinth: the mod search URL(https://api.modrinth.com/v2/search?offset=0&limit=25&query=&index=relevance&facets=[[%22categories:fabric%22],[%22versions:1.20.1%22],[%22project_type:mod%22]]) that is used can be translated get me all the mods that are in fabric category and have support for a given version. Well, there are mods there that support both fabric and forge but for example, on version 1.20.1 they have only forge(for now). The query will return them because the mod is in fabric category and also support 1.20.1 version(for forge), but when we query for the mod version we do not get any because there is no fabric version for 1.20.1 yet. e.g. https://modrinth.com/mod/fastload (is in fabric category and has support for 1.20.1(forge only) so it's shown in the search results but has no fabric version compatible(https://github.com/PrismLauncher/PrismLauncher/issues/416)
- Curseforge: third-party block or has  something similar to Modrinth

**Comment by ColonelGerdauf** [comment]
That pertains to mods listed that were never compatible in the first place. This bug report is about mods not fetching the list of available downloads the first time in a query.

**Comment by Trial97** [comment]
Then some logs from when this happens would help.

**Comment by ColonelGerdauf** [comment]
I have no clue where the bug would even be logged, for a run-time errata. And it is impractical to get a snapshot, as this problem happens erratically and even then the core of the issue would get lost.

**Comment by Ryex** [comment]
> I have no clue where the bug would even be logged, for a run-time errata. And it is impractical to get a snapshot, as this problem happens erratically and even then the core of the issue would get lost.

`~/{prism-data-path}/PrismLauncher-.log`

**Comment by Ryex** [comment]
take it directly after you reproduce the bug

**Comment by ColonelGerdauf** [comment]
I will have to close this, as I have a really hard time reproducing the bug as of late. I will have to assume that the bug was unwittingly resolved at some point in 7.x. 

If it comes up again, I will reopen this with hopefully better debug information.

**Comment by SkyanUltra** [comment]
This issue seems to have come up again recently. I've been having issues with downloading some mods like this one despite being on the right mod loader and minecraft version.

This mod is available for 1.18.2 on Forge, and the profile I'm attempting to download it onto is set to Forge 1.18.2.

![image](https://github.com/PrismLauncher/PrismLauncher/assets/29716454/2fd05f99-e1b7-4a66-8569-ed61890a4cb6)

**Comment by Trial97** [comment]
This may not be a prism issue, see my comment about this: https://github.com/PrismLauncher/PrismLauncher/issues/1044#issuecomment-1602092221

**Comment by burgrr** [comment]
> This issue seems to have come up again recently. I've been having issues with downloading some mods like this one despite being on the right mod loader and minecraft version.
> 
> This mod is available for 1.18.2 on Forge, and the profile I'm attempting to download it onto is set to Forge 1.18.2.
> 
> ![image](https://github.com/PrismLauncher/PrismLauncher/assets/29716454/2fd05f99-e1b7-4a66-8569-ed61890a4cb6)

This is happening both with mods and entire modpacks for me too. I couldn't update GT New Horizons or Ocean Outlast because there were "no valid versions" uploaded to curseforge. Yeah, right... Issue needs to be reopened.

**Comment by Trial97** [comment]
What's wrong with CurseForge?
CurseForge added a new option to block third party clients like Prism Launcher from accessing mod files, and they started to enforce this option lately. We can't allow you to download those mods directly from CurseForge because of this. However, Prism Launcher offers a workaround to enable the downloading of these mods, by allowing you to download these mods from your browser and automatically importing them into the instance. We highly encourage asking authors that opted out of client downloads to stop doing so.

**Comment by burgrr** [comment]
> What's wrong with CurseForge? CurseForge added a new option to block third party clients like Prism Launcher from accessing mod files, and they started to enforce this option lately. We can't allow you to download those mods directly from CurseForge because of this. However, Prism Launcher offers a workaround to enable the downloading of these mods, by allowing you to download these mods from your browser and automatically importing them into the instance. We highly encourage asking authors that opted out of client downloads to stop doing so.

This has nothing to do with the current issue.... Prism already has a workaround for this issue. This is about mods and modpacks alike failing to populate ANY VERSIONS WHATSOEVER for download to even begin that auto-import, and let me repeat once more that it's happening for _modpacks_ too.  As in, I cannot update modpacks. I can't update modpacks. Modpacks cannot be seen. Modpacks will not populate their versions. Prism is unable to see the versions of modpacks. Please don't derail this with unrelated info.

**Comment by Trial97** [comment]
This applies to all projects on curseforge modpacks included

**Comment by burgrr** [comment]
> This applies to all projects on curseforge modpacks included

Once again if this was the issue Prism would be able to see the version and download the mod through my browser like it has been able to since the issue you are mistaken about began over a year ago... I reiterate once again that the versions ARENT SHOWING UP IN THE DROPDOWN TO BEGIN WITH. please address the real issue

**Comment by burgrr** [comment]
> offers a workaround to enable the downloading of these mods, by allowing you to download these mods from your browser and automatically importing them into the instance.

Why isn't this "workaround" being offered if it's what you think it is?

**Comment by Trial97** [comment]
So let me get straight:
- The versions are not visible because they can't be downloaded from prism because of the third-party block that CurseForge implemented.
- There is no workaround for this third-party block as it would violate the CurseForge TOS
- If you mean that you want to have a "blocked modpacks" dialog that opens the browser for you to manually download the modpack it was already proposed as a feature request

This issue will remain closed because of the above mentions.

**Comment by burgrr** [comment]
> I will have to close this, as I have a really hard time reproducing the bug as of late. I will have to assume that the bug was unwittingly resolved at some point in 7.x.
> 
> If it comes up again, I will reopen this with hopefully better debug information.

This was not fixed

**Comment by burgrr** [comment]
> So let me get straight:
> 
>     * The versions are not visible because they can't be downloaded from prism because of the third-party block that CurseForge implemented.
> 
>     * There is no workaround for this third-party block as it would violate the CurseForge TOS
> 
>     * If you mean that you want to have a "blocked modpacks" dialog that opens the browser for you to manually download the modpack it was already proposed as a feature request
> 
> 
> This issue will remain closed because of the above mentions.

I'm already aware of the block and I'm already aware of the WORKAROUND THAT ALREADY SUPPOSEDLY WORKS FOR MODS. THE WORKAROUND' IS NO LONGER WORKING. WHAT PART OF THIS IS SO HARD TO UNDERSTAND. 

Blocked mods used to be downloaded by prism just fine and some of them STILL CAN. I am talking about PRISM FAILING TO RETRIEVE VERSIONS WHATSOEVER FOR RANDOM MODS, BLOCKED OR NOT.

**Comment by burgrr** [comment]
> So let me get straight:
> 
>     * The versions are not visible because they can't be downloaded from prism because of the third-party block that CurseForge implemented.
> 
>     * There is no workaround for this third-party block as it would violate the CurseForge TOS
> 
>     * If you mean that you want to have a "blocked modpacks" dialog that opens the browser for you to manually download the modpack it was already proposed as a feature request
> 
> 
> This issue will remain closed because of the above mentions.

Why is it doing it for mods that aren't blocked too then huh? Why am I able to download some blocked mods just fine, huh? Why does the work around randomly work and stop working, huh? I was able to use the workaround you suddenly start claiming doesn't exist just fine last night. I downloaded five instances that had tons of blocked mods and all of them downloaded just fine with the workaround that you _know_ exists, so don't play coy.

**Comment by burgrr** [comment]
Why were my comments hidden as spam? They're vital to the ONGOING ISSUE. Automoderation is a plague on humanity.

**Comment by burgrr** [comment]
> So let me get straight:
> 
>     * The versions are not visible because they can't be downloaded from prism because of the third-party block that CurseForge implemented.
> 
>     * There is no workaround for this third-party block as it would violate the CurseForge TOS
> 
>     * If you mean that you want to have a "blocked modpacks" dialog that opens the browser for you to manually download the modpack it was already proposed as a feature request
> 
> 
> This issue will remain closed because of the above mentions.

Why is it doing it for mods that aren't blocked too then huh? Why am I able to download some blocked mods just fine, huh? Why does the work around randomly work and stop working, huh? I was able to use the workaround you suddenly start claiming doesn't exist just fine last night. I downloaded five instances that had tons of blocked mods and all of them downloaded just fine with the workaround that you know exists, so don't play coy. Blocked mods used to be downloaded by prism just fine and some of them STILL CAN. I am talking about PRISM FAILING TO RETRIEVE VERSIONS WHATSOEVER FOR RANDOM MODS, BLOCKED OR NOT. Reposting to avoid the auto-mod bots so you can actually see what I'm trying to say.

**Comment by N4fta** [comment]
<img width="622" height="316" alt="Image" src="https://github.com/user-attachments/assets/23f4099f-9f24-46dd-9b39-e5a47bc9e944" />
30 Oct 2025 and "No version is available!" when downloading certain modpacks is still an issue

**Comment by SkyanUltra** [comment]
I've confirmed that this issue is happening on mods which don't even block client downloads as well on occassion. attempting to download a mod from Prism from the same provider (happens most often with CurseForge, has happened with Modrinth as well) will sometimes bring up the same incorrect "No version is available!" before getting fixed upon re-launching the client.

Not only does this issue need to still be fixed, but there should also be an actual indicator that "No version is available" isn't being shown for the sole fact that Prism can't download them due to being blocked, and instead display a unique "Download blocked by author!" to actually give the user an idea of why this happens instead of them out right assuming that there's just no available version at all, with some tip to let the user know they can still download it directly from the provider site.

**Comment by Logini228** [comment]
Still happening, been going crazy for 2 hours before finding out that the issue was that Prism silently ignored some mods while helping to install manually others

**Comment by adex345** [comment]
Getting same thing on new snapshot. While using Modrinth.

**Comment by SkyanUltra** [comment]
I feel like this issue warrants being re-opened if its still this large of a problem, its incredibly confusing from a user standpoint and doesn't convey the problem well enough.
