### ISSUE TITLE
update rsource pack and shaders

### ISSUE THREAD

**Issue by pizzav-xyz** [PrismLauncher/PrismLauncher#1207]
### Role

ease of life

### Suggestion

Track metadata for resource packs and shaders and allow checking for updates

### Benefit

none

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
Benefit: none.
:laughing: 

Seriously though, this is very useful functionality missing!

**Comment by UltraBlackLinux** [comment]
I don't see why you'd have to necessarily do this via a github link, but in general an RP downloader/updater like ATLauncher has it would be very nice

**Comment by TheKodeToad** [comment]
yeah, i meant from modrinth in my response

**Comment by Poopooracoocoo** [comment]
Thank you Kode Toad for #1588!!

**Comment by TheKodeToad** [comment]
I forgot to link this issue.

I haven't really got anything working :laughing:

**Comment by pizzav-xyz** [comment]
When added?

**Comment by Trial97** [comment]
Unsure: nobody picked this up

**Comment by TheKodeToad** [comment]
My PR doesn't require a lot more work IIRC.

**Comment by Mortycio** [comment]
Since my post has been closed, I'll write my experience here.

The request is very simple: add a button to update all resource packs together, just like it happens for mods.

There is a button to update all the mods together,

![mods update button](https://github.com/PrismLauncher/PrismLauncher/assets/113641947/73afa208-5dd4-4702-9987-988d00040968)

but there isn't one for the resource packs, nor for the shaders, let alone for resources like "LWJGL" or "Fabric Loader" (in my case, since I use Fabric).

![version missing update button](https://github.com/PrismLauncher/PrismLauncher/assets/113641947/2b56f016-957d-4eec-9060-fd2c15a128a3)

By now, I've accumulated 39 resource packs, most of them are the classic "better x", "better y", etc., others make specific objects 3D, others completely change textures or add animations...
In short, to keep them updated I have to go back and re-download them, and ABOVE ALL Prism doesn't tell me the exact version installed (it only shows numbers like 15, 18, 22 etc.)

![rp missing update button](https://github.com/PrismLauncher/PrismLauncher/assets/113641947/9f260d08-1e78-4359-a2ab-aee3d879281a)

so I have to open the links on Modrinth/Curseforge, go to the "versions" section, check which version I have by filtering the Minecraft version, and from there figure out which one is the right one.

ㅤ
ㅤ

P.S. when trying to download resource packs, there is no button to filter the results based on the Minecraft version of the instance.

![mods filter button](https://github.com/PrismLauncher/PrismLauncher/assets/113641947/98b84d00-d8f4-483b-904f-a3bce1651401)
![rp missing filter button](https://github.com/PrismLauncher/PrismLauncher/assets/113641947/0f1c6bd7-381e-4f72-ac65-3f76ed335847)

ㅤ
ㅤ

P.P.S. the shader packs installed don't appear on the screen.

![shader missing update button](https://github.com/PrismLauncher/PrismLauncher/assets/113641947/8a9723ea-552b-40e6-aa26-e7deb10d26d4)

**Comment by TheKodeToad** [comment]
Updated the issue to reflect what realistically will happen
