### ISSUE TITLE
"PrismLauncher" in Windows setup

### ISSUE THREAD

**Issue by RuiNtD** [PrismLauncher/PrismLauncher#126]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

The Windows setup says "PrismLauncher" everywhere instead of "Prism Launcher"
![](https://i.imgur.com/l7Ritzg.png)
![](https://i.imgur.com/I6KIIoN.png)

### Steps to reproduce

1. Download Windows setup
2. Run Windows setup

### Suspected cause

I blame RegEx.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FayneAldan** [comment]
![](https://i.imgur.com/l7Ritzg.png)
![](https://i.imgur.com/I6KIIoN.png)

**Comment by tobimori** [comment]
This issue is happening similarly on macOS in the Application itself (menu bar). 
Also, the name of the .app file is `PrismLauncher.app` instead of `Prism Launcher.app`

<img width="290" alt="CleanShot 2022-10-19 at 21 29 51@2x" src="https://user-images.githubusercontent.com/29142128/196786004-2f102826-47f4-410f-84d5-5a513cd99ff1.png">

**Comment by ZombieNub** [comment]
There appear to be many instances where Prism Launcher is inappropriately referred to as "PrismLauncher". Unfortunately, there are points in which it is used appropriately, so a simple find-and-replace may not be viable.
