### ISSUE TITLE
Trying to export 1.7.10 pack carshes prism

### ISSUE THREAD

**Issue by MiusR** [PrismLauncher/PrismLauncher#1297]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

When attempting to export an instance of the Lost Era Modpack for 1.7.10 by clicking the export button on the right-hand side, the app creates a zip with a corrupted file inside and then freezes. It stops only when forcefully stoped.

### Steps to reproduce

* Have an instance of Lost Era
* Click on export
* Select an export place
* Crash

### Suspected cause

I don't understand what it's causing this since it works with other modpacks like fabulously optimized.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Did you have huge words/backups that you tried to export?
The task doesn't report back the status when exporting, but it may still export them(it looks like it freezes but it does the thing in the backend). The progress reporting was already fixed in develop(https://github.com/PrismLauncher/PrismLauncher/issues/245)
Did you try to wait more?

**Comment by Trial97** [comment]
Closing this as there were no updates.
If it still happens please let us know.
