### ISSUE TITLE
Use a fixed width in the main sidebar

### ISSUE THREAD

**Issue by santiagocezar** [PrismLauncher/PrismLauncher#130]
This is the [preliminary Flatpak build](https://github.com/flathub/flathub/pull/3596#issuecomment-1284452111) of Prism Launcher (5.0 + Qt6). The sidebar changes size depending on the name of the instance.

[fun](https://user-images.githubusercontent.com/48573316/196791002-0fc0f0dc-19e2-4dc4-a70f-9ff0ec27bd96.webm)

Clearly there is a width constraint set, because the text wraps when the name gets really long. IMO the width should be always set to that.

(also this is technically a duplicate of https://github.com/PolyMC/PolyMC/issues/925, but it didn't get any response and this is a new repo anyway)

**Comment by Scrumplex** [comment]
Hopefully we can fix this up in #30

**Comment by IdrisQe** [comment]
Yeah this kinda looks bad the way it is currently. That said, adding onto this, instead of just a fixed width, could we have a right-click option to lock the sidebar, and then the ability to click the edge of it and drag to resize it manually? I feel like that would fit a lot more use-cases since it would allow for user-end customization.

Also I was going to report this myself but realized someone already made an issue about it, but I already recorded the gif so here it is anyway. Shows the full sidebar, not that it really needs to be seen given it's already going to get fixed.
![gif](https://user-images.githubusercontent.com/40530630/196846592-e1802892-9186-416f-9b0e-89348fb232be.gif)

**Comment by Scrumplex** [comment]
Similar to #69. Let's track this there
