### ISSUE TITLE
Add ability to choose very small heap sizes

### ISSUE THREAD

**Issue by embeddedt** [PrismLauncher/PrismLauncher#1318]
### Role

I aggressively optimize Minecraft

### Suggestion

Add a (possibly hidden) option to allow me to set a maximum heap size below 128MB

### Benefit

It's easier than having to find an alternative way to launch the game/supply arguments to bypass the GUI check

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I'll leave this screenshot here as proof that I'm not just trolling.

![2023-07-05_19 59 33](https://github.com/PrismLauncher/PrismLauncher/assets/42941056/fdf0fba9-50ce-4602-9a16-478951b30932)

**Comment by Frontear** [comment]
ive got to ask, how do you get minecraft running at that memory? i was under the impression that at that low heap, youd constantly be having hard GC freezes, but clearly you wouldnt do it if that was the case.

**Comment by embeddedt** [comment]
A couple things:

* This is multiplayer, so the pressure on the GC is reduced.
* The baseline, static heap usage is hovering somewhere around 100MB, which leaves about 20MB of headroom for the young generation.
* Since the heap is so small, even if the GC runs frequently, the pause time is very short, so it is possible to sustain ~60fps without seeing stutter.
* I have put many hours of work into the game to cut down on unnecessary bloat.

**Comment by Frontear** [comment]
Wow! I'd like to know your modlist if you'd be okay with sharing, its quite fascinating. I've always used ModernFix myself, but had no idea it could make minecraft work under such dire conditions.

**EDIT** I know see what you mean, you mean BELOW 128, which it silently rejects. My apologies

~~Though going back to the original issue, I dont seem to see anything that's stopping you from launching on 128MB at the very least. I just successfully managed to launch an instance, well before it hung and crashed because it had far too many mods, but prism did let it launch. I did notice there was a GC argument for SurviverRatio that was mistuned given my heap size became so egregiously small, so removing it allowed me to launch fine. Do you think you could share whatever error message there is when trying to launch on small heap sizes?~~

**Comment by embeddedt** [comment]
I'll send you the mod list later when I'm on my PC. The issue is that the
GUI simply refuses to accept any value smaller than 128MB, and forcefully
increases it back to that.

**Comment by embeddedt** [comment]
I've made a [FAQ page](https://github.com/embeddedt/ModernFix/wiki/Ultra%E2%80%90Low-Memory-Footprint) with some more details of how to achieve this for anyone who's curious. Some of the optimizations are fairly aggressive and so they have to be turned on manually in the ModernFix config.

**Comment by ghost** [comment]
To anyone reading, here's a screenshot from me

![2023-07-08_18 18 39](https://github.com/PrismLauncher/PrismLauncher/assets/85982640/f871bbbf-d21b-42df-bdc1-f1ab73be40f2)
