### ISSUE TITLE
Add support for NeoForge modloader 

### ISSUE THREAD

**Issue by 0xRogu** [PrismLauncher/PrismLauncher#1356]
### Role

I play modded minecraft and run modded servers.

### Suggestion

Add support for the Neo Forged modloader (a hard fork of Forge including all the team excluding LexManos)

### Benefit

Neo Forged will be the only replacement for Forge unless LexManos gets a whole new team or someone else decides to fork it.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The repo for neo forged is here: https://github.com/neoforged/NeoForge they will contain 100% comparability with Forge until the next minecraft release then then they're going to break hard, to fix all of the things that should have been fixed years ago.

**Comment by mcg-anon** [comment]
The only reason why they forked now already, is because one of their discord friends leaked their plans and they freaked out and had no other choice. That one discord friend is now claiming that he got hacked, but that is very questionable.
As you correctly say, there will be no difference between neoForge and Forge till the next release.

Just something to consider, because for the enduser, it might be confusing to have two options for the exact same thing.

I would wait till they actually fork and differ from forge.

**Comment by TheKodeToad** [comment]
citation needed for the plan-leaking... :thinking:

**Comment by mcg-anon** [comment]
@TheKodeToad i don't think that this is the right place for discord drama, that's why i didn't even name that discord friend.
Fact is that NeoForge isn't planning on doing anything till the next release.
OP is sugarcoating it by saying:
`100% comparability with Forge` and `the next minecraft release then then they're going to break hard`
but he doesn't say why that is the case and why they can't fix those things `that should have been fixed years ago` already now.
I just gave you a little explanation without going into too much details.

**Comment by TheKodeToad** [comment]
Well, I agree this isn't something which should be added atm
It may even be harmful to the NeoForged project

The reason for asking was I wasn't sure that it was true, that's all :P

**Comment by Tkain** [comment]
NeoForged just put out [their first public download](https://neoforged.net/) and [their Maven](https://maven.neoforged.net) seems to be up and running, so I think it's probably fine to add it to Prism's development releases at this point. The team is labelling these releases as primarily for testing, so it can probably be kept from 7.2 if that comes out sooner than expected, but I think it's good to test it out now in any case.

Also, relevant issue: https://github.com/ZekerZhayard/ForgeWrapper/issues/12

**Comment by Scrumplex** [comment]
I was looking at this a few days ago, and NeoForge's maven is different to Forge's maven. I will need to invest some time into writing new logic for pulling in NeoForge versions

**Comment by TheKodeToad** [comment]
https://github.com/ZekerZhayard/ForgeWrapper has now added support for NeoForge (and possibly other forks)!

**Comment by Rushmead** [comment]
@Scrumplex I have put together some _very_ rudimentary meta scripts based on the existing forge ones for NeoForge here https://github.com/Gaz492/meta, though currently I also add them to the Forge versions list so that they can be installed without needing a new build of PrismLauncher. Hopefully this is of help to you, I'd be happy to tidy them up and PR them in if that would be welcomed.

**Comment by Scrumplex** [comment]
> Hopefully this is of help to you, I'd be happy to tidy them up and PR them in if that would be welcomed.

This looks really good so far! We want to keep Forge and NeoForge separate, as they are technically two different projects. This will depend on #1230 though.

**Comment by Scrumplex** [comment]
I have started work based on your commit in https://github.com/PrismLauncher/meta/tree/neoforge

I will need a reminder to definitely thank you for your help in our release notes for 8.0 :D

**Comment by Scrumplex** [comment]
Tracking this in PrismLauncher/meta#21

**Comment by Stabington** [comment]
Curseforge and Modrinth have made separate categories for Forge / Neoforged mods, which currently makes the launcher consider NeoForged mods as incompatible with a Forge install, even when they supposedly are interchangeable. 
Need to manually download Immersive Engineering for example.

**Comment by TheKodeToad** [comment]
> which currently makes the launcher consider NeoForged mods as incompatible with a Forge install

~~Not in Prism Launcher, no~~
~~Although future versions of NeoForge it will be incompatible so there's a version check~~
If a mod author intentionally makes it NeoForge-only it makes sense that they won't show up for Forge instances.

**Comment by ajaxnotmeta** [comment]
wich made NeoForge Needed to be a new instaces i Prism, since i already had many issues with Forge mod already with my friends doing modpacks, and i know AT launcher exist too but its cumbersome to have whoping 5 launcher with 5 different instance folder just to play mods
