### ISSUE TITLE
Make portable version have a dedicated user data directory

### ISSUE THREAD

**Issue by he3als** [PrismLauncher/PrismLauncher#139]
### Role

I am a Prism Launcher user and Prism Launcher Scoop packager.

### Suggestion

I want there to be a dedicated user data directory folder for the portable version of Prism Launcher on Windows.

### Benefit

It would be more organised (more simple and easy) and it would mean that I could make a portable Scoop package for Prism Launcher (currently I can not due to this issue https://github.com/ScoopInstaller/Scoop/issues/1372#issuecomment-304462955).

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Scrumplex** [comment]
You can always set a custom directory using `prismlauncher -d <path>` and `prismlauncher.exe -d <path>`

**Comment by he3als** [comment]
I think that it should be in a 'User data' directory inside of the portable folder by default though. It would be cleaner and easier for packaging.

I have found a way around the Scoop limitation now anyways so it is not a limitation, but I am still not sure if people would want to have a portable Prism Launcher Scoop package, because global installations of Scoop will have issues with permissions. However, I am not sure, maybe there can be workarounds for that too.

**Comment by SmilerRyan** [comment]
Not only does this make things more organized and easy to know what is application files and data, but it also helps if someone needs to reset their launcher, since they just need to know to delete the data folder, and make a new one.

I'd like to see this done how Visual Studio does it, instead of creating a file called portable.txt to tell it to use the app directory to store all of it's files, it looks for a folder called "data" first, and if it exists stores everything there instead of appdata or the app's root directory.

Currently it looks like this in the app's root directory:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/14893385/e83d2a34-1579-4a16-bef5-108bc6c7f900)

And with the data directory present, it would look like this, with the data folder containing the same as it would do in appdata:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/14893385/1070d108-c2af-4d8a-9c63-f4d3a8cf093f)

**Comment by Trial97** [comment]
Why not create a batch file with something like this:
  prismlauncher.bat
```
prismlauncher.exe -d data
```
and use that instead of the original executable?

**Comment by he3als** [comment]
That's kind of hacky, and I think that it should be default to have a dedicated user data directory for organisation purposes meaning an improved user experienced, as well as slightly easier package management for Scoop.

**Comment by Trial97** [comment]
Feel free to express any changes to the folder name in the opened PR: #1529
