### ISSUE TITLE
Info button next to cat selection does nothing

### ISSUE THREAD

**Issue by SirenGlitch** [PrismLauncher/PrismLauncher#1457]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

This program uses Qt version 6.5.1.

### Description of bug

The info button next to the cat selection does nothing

### Steps to reproduce

Open settings, Launcher tab, User Interface. Click the "i" button to the right of the cat selection.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
It's not meant to do anything

**Comment by SirenGlitch** [comment]
> It's not meant to do anything

Then why is it there if it does nothing?

**Comment by TheKodeToad** [comment]
You're not meant to click it, it has a tooltip

**Comment by TheKodeToad** [comment]
Even if it's not ideal, it'll probably be removed or changed at some point :P

**Comment by SirenGlitch** [comment]
> You're not meant to click it, it has a tooltip

The whole area has a tool tip though, doesn't matter where you're mouse is along as its in the "Cat" area

> Even if it's not ideal, it'll probably be removed or changed at some point :P

I hope so, very confusing

**Comment by TayouVR** [comment]
the reason that little i is there is, because people didn't understand what the cat did, especially on the setup wizard, but also on the settings page. Hence I added that little I icon.
I used a button for it simply because in Qt that was a very easy way to draw an icon with a tooltip. I hadn't actually realized until like 10 seconds ago, that when you click it it did an animation...

But yeah, its gonna get changed or maybe even just removed.
