### ISSUE TITLE
Support MangoHud detection without LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by Scrumplex** [PrismLauncher/PrismLauncher#165]
From: https://github.com/flathub/flathub/pull/3596#discussion_r1000419972

> I see. Although I'd like a point out that `dlopen`'ing `libMangoHud.so` isn't a proper way to detect if MangoHud is installed, because `libMangoHud.so` isn't supposed to be present in the linker search path at all. For example, Fedora explicitly prohibits installing unversioned libs to default libdir, so this check won't work with Fedora's `mangohud` package.

Alternative approach:
Detect `mangohud` wrapper script and extract the relevant env vars from there.

**Comment by gasinvein** [comment]
Another idea: you probably can extract the MangoHud libs install path from it's vulkan layer manifest. The manfest is a json file that has `library_path` property containing the full path to the lib, e.g.
```json
{
    "file_format_version" : "1.0.0",
    "layer" : {
      ...
      "library_path": "/usr/lib/extensions/vulkan/MangoHud/$LIB/libMangoHud.so",
      ...
    }
}
```

**Comment by theofficialgman** [comment]
as noted in the discord. the official mangohud install script does not place the .so files in the library path either. so this is intended functionality. https://github.com/flightlessmango/MangoHud/blob/96f72e2352616f0c5e28a80551e35d2fd16d4fe4/build.sh#L227-L269

as mentioned above, I think the vulkan manifest library_path is a good solution. since it accomidates both packagers installations, the official buildscript, and default meson build options

default meson options build does place them in the library path:
```
      "library_path": "/usr/\$LIB/libMangoHud.so",
```

default buildscript:
```
      "library_path": "/usr/lib/mangohud/$LIB/libMangoHud.so",
```

**Comment by Scrumplex** [comment]
I am wondering how the launcher could figure out *where* to look for vulkan layer manifests

**Comment by gasinvein** [comment]
> I am wondering how the launcher could figure out _where_ to look for vulkan layer manifests

[The spec describes](https://vulkan.lunarg.com/doc/view/1.2.162.0/mac/loader_and_layer_interface.html#user-content-linux-layer-discovery) the way it does layer discovery - by looking in paths specified in `XDG_CONFIG_DIRS` and `XDG_DATA_DIRS`. Doing the same should be easy enough, but the problem is, on some hosts vulkan-loader can be patched to look in some different path not specified in `XDG_*_DIRS` (sadly, this is the case with freedesktop-sdk used by flatpak).
Edit: vulkan-loader doesn't seem to look for layers in `XDG_CONFIG_DIRS`, only in `XDG_DATA_DIRS`.

**Comment by DioEgizio** [comment]
Didn't https://github.com/PrismLauncher/PrismLauncher/pull/569 fix this?

**Comment by Scrumplex** [comment]
Yes
