### ISSUE TITLE
Launcher Crashes when Launching an Instance with an Emoji in its Name

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [PrismLauncher/PrismLauncher#1659]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

Qt 6.5.1

### Description of bug

The launcher crashes when loading an instance with an emoji in its name.

### Steps to reproduce

- Create an instance with an emoji
- Press launch

### Suspected cause

Something doesn't like weird characters

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by SpikyStars** [comment]
I'm able to recreate what I believe is this bug (or closely related) on Prism 8.0 not using an emoji, but by using Chinese characters. I'm on Windows 10.

(if it helps for testing, the string I used as the instance name that caused the crash is this:
`喵喵喵喵喵喵喵喵`)

Apparently someone on Reddit said that Cyrillic characters being in the instance name also caused the launcher to crash on instance launch. 
My suspicion is that UTF-8/Unicode characters in general are making things funky.

**Comment by Poopooracoocoo** [comment]
For reference [here's](https://www.reddit.com/r/fabricmc/comments/182886y/so_real/) one Reddit post about using Cyrillic as instance names. The post is about the CurseForge App but the comments are where other people try to reproduce in various launchers.

**Comment by FrnkPsycho** [comment]
I reproduced quite the same issue on Linux using curseforge implementation but instead of crashing it dumped error log:
![图片](https://github.com/PrismLauncher/PrismLauncher/assets/61046277/08f50818-ac65-4737-ba35-b48c4fb1caab)

The modpack page is [https://www.curseforge.com/minecraft/modpacks/all-the-mods-gravitas2](here)

IMO prism just copy the name of modpack on curseforge to path but java file library does not support tricky unicode characters.

**Comment by kce4981** [comment]
I found out the issue is calling the win api`GetShortPathNameW` with non-exist file location.

https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/minecraft/launch/LauncherPartLaunch.cpp
line 138
```c++
auto natPath = minecraftInstance->getNativePath();
#ifdef Q_OS_WIN
    if (!fitsInLocal8bit(natPath)) {
        args << "-Djava.library.path=" + shortPathName(natPath);
    } else {
        args << "-Djava.library.path=" + natPath;
    }
#else
    args << "-Djava.library.path=" + natPath;
#endif
``` 
The `natPath` doesn't exist all the time, but it only crashes the launcher when the instance location contains unicode characters because it gets passed into `shortPathName`. 

line 71
```c++
#ifdef Q_OS_WIN
// returns 8.3 file format from long path
#include <windows.h>
QString shortPathName(const QString& file)
{
    auto input = file.toStdWString();
    std::wstring output;
    long length = GetShortPathNameW(input.c_str(), NULL, 0);
    // NOTE: this resizing might seem weird...
    // when GetShortPathNameW fails, it returns length including null character
    // when it succeeds, it returns length excluding null character
    // See: https://msdn.microsoft.com/en-us/library/windows/desktop/aa364989(v=vs.85).aspx
    output.resize(length);
    GetShortPathNameW(input.c_str(), (LPWSTR)output.c_str(), length);
    output.resize(length - 1);
    QString ret = QString::fromStdWString(output);
    return ret;
}
#endif
``` 
Having non-exist file path passing into `GetShortPathNameW` makes the length valued zero, which crashes the launcher when calling `output.resize(length - 1);`

https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getshortpathnamew
> If the function fails for any other reason, the return value is zero. To get extended error information, call [GetLastError](https://learn.microsoft.com/en-us/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror).

Calling `GetLastError` returns the error code [0x2 ERROR_FILE_NOT_FOUND](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-).

I tried manually creating a folder named `natives` inside instance folder and the game launched without issues.
