### ISSUE TITLE
MacOS 14 (Sonoma): Unable to open app, saying update needed

### ISSUE THREAD

**Issue by samip5** [PrismLauncher/PrismLauncher#1920]
### Operating System

macOS

### Version of Prism Launcher

Unsure as won't launch

### Version of Qt

Unsure as won't launch

### Description of bug

The app will not launch that was downloaded from https://prismlauncher.org/download/mac/ today 5st of Dec, and universal one was the one I tried.

<img width="241" alt="Screenshot 2023-12-05 at 14 19 20" src="https://github.com/PrismLauncher/PrismLauncher/assets/1703002/2e28e21b-aae7-48c8-82a5-15c576f49191">

### Steps to reproduce

- Go to https://prismlauncher.org/download/mac/
- Download universal on Sonoma MacOS
- Try to open the extracted app
- Have it fail due to "cannot be opened because Apple cannot check it for malicious software"

### Suspected cause

Apple

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment]
That's normal. Just right click it and press open. There should be an option to open regardless. Something along the lines of "are you sure you want to open this app" not word for word but the general idea

The only reason that's there is because it's not a signed app, or whatever it's called, which is basically an expensive subscription. But you can open any application regardless of it

**Comment by samip5** [comment]
Ah so that's just MacOS Guardian being Guardian. :)
