### ISSUE TITLE
FTB modpacks are not listed

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [PrismLauncher/PrismLauncher#2002]
### Operating System

`Arch Linux`

### Version of Prism Launcher

8.0qt5 (from the `AUR`)

### Version of Qt

5

### Description of bug

The FTB mod packs are not listed
![image](https://github.com/PrismLauncher/PrismLauncher/assets/30759571/94a55754-497d-4e33-87c3-8f841013133d)
Note: all other mod pack categories work, including FTB legacy.

Note expected behavior from the wiki:
https://prismlauncher.org/wiki/help-pages/ftb-platform/

### Steps to reproduce

* start prism launcher 
* click "Add Instance" (top left)
* select category "FTB App Import" (left column)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
The documentation there is outdated as the FTB was removed(more info about here: https://prismlauncher.org/news/ftb-removal/)
As for the FTB App Import option was added in the latest 8.0 but is not for downloading FTB packs but instead importing them from the FTB App(they need to be downloaded over there in order to work).
Right now another limitation of this is the fact that the import only looks at the default FTB App instances directory and if you use a custom one the instances will not be detected( see: https://github.com/PrismLauncher/PrismLauncher/issues/1830 )
