### ISSUE TITLE
Pre-release mod downoloader

### ISSUE THREAD

**Issue by GuyFromTheInternet** [PrismLauncher/PrismLauncher#2181]
### Role

I play modded minecraft, and some times beta-alpha modded minecraft

### Suggestion

Downoload mods for pre-release

### Benefit

It would be cool for people who have no idea how much work people put in these early mods that dissapeared with minecraft updates

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Sadly there isnt a proper website that hosts downoloads for there mods, but I'm sure theres a workaround right? You could propably host those files on the website since they arent really that much of them, https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/1344337-historical-one-stop-mod-shop-last-updated-04-05, this is a forum post that contains a lot of old mods with surprisingly working links! Theres also "Modification Station", a discord server dedicated to modding these old versions, but for some reason they have invite links disabled.

**Comment by TheKodeToad** [comment]
There's a nice centralised place for old mods: https://mcarchive.net/
I don't think we'll add launcher-integrated downloading for jarmods (which I'm pretty sure is virtually every mod for alpha/beta) because:
- They redistribute Minecraft's code
- We don't have permission from the authors to redistribute the mods either
