### ISSUE TITLE
Prism crashes randomly

### ISSUE THREAD

**Issue by SuperZekes** [PrismLauncher/PrismLauncher#2227]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.3.0

### Description of bug

I made an install tried to run it and it just crashed 🙃

### Steps to reproduce

Well it seems this may only be an issue for me as said above I just made an install ran it and it crashed. When running in the default MC launcher it worked just fine.

### Suspected cause

Windows is known to suck I don't think it's a bug with the software

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TayouVR** [comment]
you need to update, you are on an ancient version from over a year ago and a lot of bugs have been fixed since.
download the latest version from https://prismlauncher.org/download/ we also now have a built in updater in the recent releases, so you should be able to update in the future right in the launcher.

If you previously installed Prism Launcher through the installer, just download the latest installer and it will update to the latest version. Your instances and worlds will be safe during this procedure.

Reopen this issue if you still experience the issues in 8.2

**Comment by SuperZekes** [comment]
I have no issues on 8.2 I download prism all the way back in 5.0 and did not know there were new releases.
Thank you!
- SuperZekes
