### ISSUE TITLE
Prism unable to access websites in Russia on Windows 10

### ISSUE THREAD

**Issue by maskersss** [PrismLauncher/PrismLauncher#2260]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.2, portable

### Version of Qt

Qt 6.6.2

### Description of bug

In Russia, Prism is unable to access several websites, including mclo.gs, Modrinth, and the Forge maven.
The issue appears to be specific to Russia and doesn't seem to happen on Windows 11.

possibly relevant:
- multimc appears to work fine
- Modrinth launcher is having the same issues
- OBS can't connect to twitch, also specific to Russia and happens since yesterday: https://obsproject.com/forum/threads/30-1-1-failed-to-get-token-from-remone-connection-timed-out-after.174474/
Prism log from a presh portable installation trying to launch 1.20.4 forge: https://mclo.gs/mz9RjY0

### Steps to reproduce

- be in Russia
- use Windows 10
- go to Add Instance > Modrinth
- it will not load

### Suspected cause

something being blocked in Russia

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by lordofpipes** [comment]
This issue is related to the Russian censors &mdash; specifically, ISPs in European Russia are breaking TLSv1.2 on Cloudflare, causing connections to time out.

The current workarounds are to either update to an operating system that natively supports TLSv1.3 (such as Windows 11, or any macOS/Linux that has OpenSSL 3), or to use a VPN.

Modrinth discussion of the issue:

![image](https://github.com/PrismLauncher/PrismLauncher/assets/68424788/b7e089fb-a72d-4937-8f0d-fd8bf1118760)

**Comment by lordofpipes** [comment]
Here are two workarounds:

## Method 1: Update your OS

### Windows

Update to Windows 11 or above.

### MacOS

~~Update to macOS 10.15 or above. Not tested, don't count on it.~~

MacOS users may need to wait until Qt is updated.

### Linux

Stop using Debian 8/9 or CentOS 7. These versions were released almost 10 years ago.

## Method 2: I don't want to update my OS

### Windows

- Run Windows update to bring your OS to the latest version.
- Press `Win + R` and type `inetcpl.cpl` to open `Internet Properties`.
- Browse to the `Advanced` section and check `Use TLS 1.3 (experimental)` to enable TLS 1.3.

![image](https://github.com/PrismLauncher/PrismLauncher/assets/68424788/ab19ddd7-020e-4723-9eea-915af9ac45e3)

- Press `Win + R` and type `regedit` to open `Registry Editor`.
- Browse to the path `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client` and double click on `Enabled`
- In the `Value data` field, change the value to `1` and select `OK`.

![image](https://github.com/PrismLauncher/PrismLauncher/assets/68424788/cdcf9db4-5f55-4ebc-ad00-3893a156f3ee)

- Restart your PC

### MacOS

~~[These instructions](https://secure.plusplushosting.net/knowledgebase/1772/How-to-enable-TLS-1.3-in-Mac-Safari.html) *might* work on some older macOS versions. Not tested, don't count on it.~~

MacOS users may need to wait until Qt is updated.

### Linux

Statically compile the latest OpenSSL 3 (or the latest 1.1.1) instead of using your distro's version. The Flatpak and the AppImage are likely to avoid the issue, too.

**Comment by DioEgizio** [comment]
> This issue is related to the Russian censors — specifically, ISPs in European Russia are breaking TLSv1.2 on Cloudflare, causing connections to time out.
> 
> The current workarounds are to either update to an operating system that natively supports TLSv1.3 (such as Windows 11, or any macOS/Linux that has OpenSSL 3), or to use a VPN.
> 
> Modrinth discussion of the issue:
> 
> ![image](https://private-user-images.githubusercontent.com/68424788/318374072-b7e089fb-a72d-4937-8f0d-fd8bf1118760.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjEyNjcsIm5iZiI6MTcxMTk2MDk2NywicGF0aCI6Ii82ODQyNDc4OC8zMTgzNzQwNzItYjdlMDg5ZmItYTcyZC00OTM3LThmMGQtZmQ4YmYxMTE4NzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA4NDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMDE1Y2M3YjZhODM1MjFlNTIxNzZlM2Q5NjE5OGJhNWIzZjYwNmU2Y2E5MTQ0M2QzMzI4NjFhOWE4Y2RiY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d0r7Z2SDL-h9ImptSe7VT7XVeDuwWU4nIvKSXz3NZCU)

The thing is: how would it work on multimc then? MMC uses a version of openssl from 2017 on windows

**Comment by DioEgizio** [comment]
Also this won't work on macOS. Qt Network on macOS uses an old API which is deprecated and wasn't upgraded to the new one (Network.framework) because it's too high level and won't work for Qt. This old API (SecureTransport) doesn't support TLS 1.3. See https://www.qt.io/blog/qt-network-in-qt-6 for more info (this is old, nowadays Qt supports tls 1.3 on the schannel backend)

**Comment by DioEgizio** [comment]
> Statically compile the latest OpenSSL 3 instead of using your distro's version. The Flatpak is likely to avoid the issue, too.

[OpenSSL supports TLS 1.3 since openssl 1.1.1.](https://wiki.openssl.org/index.php/TLS1.3). Practically every distro where prism works on already should work on TLS 1.3

**Comment by lordofpipes** [comment]
> > Statically compile the latest OpenSSL 3 instead of using your distro's version. The Flatpak is likely to avoid the issue, too.
> 
> OpenSSL supports TLS 1.3 since openssl 1.1. practically every distro where prism works on already should work on TLS 1.3

I think you might be right. At first I was thinking "this surely must only affect CentOS 7 users" but I erred on the side of caution with my advice because sometimes the enterprise-y distributions have stuff disabled until it is considered ready. Edited to reflect this.

**Comment by DioEgizio** [comment]
> Stop using Debian 8 / CentOS 7. These versions were released almost 10 years ago.

Add Debian 9 (also discontinued), it had [openssl 1.1.0](https://web.archive.org/web/20201111232513/https://packages.debian.org/stretch/openssl) while tls 1.3 was added to openssl 1.1.1

**Comment by R2kip** [comment]
@lordofpipes 
![image](https://github.com/PrismLauncher/PrismLauncher/assets/56793105/7b47a7bf-3b60-4e3d-8394-e89ca25029e3)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/56793105/c9a2f749-9c6d-472b-b95d-24475910ac5d)
The computer was restarted several times

**Comment by Linaryx** [comment]
![image](https://github.com/PrismLauncher/PrismLauncher/assets/99946996/3f8365b2-79aa-4fda-a4a8-246a37584318)
i dont have a tls 1.3 on regedit

**Comment by lordofpipes** [comment]
> i dont have a tls 1.3 on regedit

Weird. Have you confirmed that you are running Windows 10 version 1903 or later? Maybe you haven't gotten the update.

**Comment by Linaryx** [comment]
> > i dont have a tls 1.3 on regedit
> 
> Weird. Have you confirmed that you are running Windows 10 version 1903 or later? Maybe you haven't gotten the update.

i create the section by itself
![image](https://github.com/PrismLauncher/PrismLauncher/assets/99946996/ee802b85-2c49-45a5-ae8f-015a35555cd0)

**Comment by Linaryx** [comment]
> > > i dont have a tls 1.3 on regedit
> > 
> > Weird. Have you confirmed that you are running Windows 10 version 1903 or later? Maybe you haven't gotten the update.
> 
> i create the section by itself
> ![image](https://github.com/PrismLauncher/PrismLauncher/assets/99946996/ee802b85-2c49-45a5-ae8f-015a35555cd0)
> 

Square brackets if removed) Now let's check the functionality

**Comment by Linaryx** [comment]
> > > > i dont have a tls 1.3 on regedit
> > > 
> > > Weird. Have you confirmed that you are running Windows 10 version 1903 or later? Maybe you haven't gotten the update.
> > 
> > i create the section by itself
> > ![image](https://github.com/PrismLauncher/PrismLauncher/assets/99946996/ee802b85-2c49-45a5-ae8f-015a35555cd0)
> > 
> 
> Square brackets if removed) Now let's check the functionality

Does not work (

**Comment by Linaryx** [comment]
> > i dont have a tls 1.3 on regedit
> 
> Weird. Have you confirmed that you are running Windows 10 version 1903 or later? Maybe you haven't gotten the update.

![image](https://github.com/PrismLauncher/PrismLauncher/assets/99946996/d4d3bdc6-5f04-483a-88f3-7ececb5cc8f3)

**Comment by R2kip** [comment]
@00Linar00 У тебя кастомная сборка винды?
Do you have a custom build of Windows?

**Comment by Linaryx** [comment]
> @00Linar00 У тебя кастомная сборка винды?
> 

Я не знаю

**Comment by R2kip** [comment]
https://support.modrinth.com/en/articles/9138172-modrinth-app-doesn-t-work-in-russia

**Comment by Linaryx** [comment]
It's working! I updated my windows and selected tls 1.3 manually now everything works!!!!

**Comment by R2kip** [comment]
Lol, I wrote to the Internet provider, they said that there were no locks on their part and after that everything was fixed. Am I the only one?

**Comment by Trial97** [comment]
Does this still happen?

**Comment by DioEgizio** [comment]
Nope, afaik russia reverted the ban

**Comment by Trial97** [comment]
Can we close this then?

**Comment by maskersss** [comment]
yeah, i don't see why not
