### ISSUE TITLE
No valid version found for a mod

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#2449]
### Operating System

Linux

### Version of Prism Launcher

8.3

### Version of Qt

6.2.4

### Description of bug

App says that there's "No valid version found for a mod" when I see that it is clearly available for download on Curseforge (MinersAdvatage for 1.12.2 Forge), HMCL can download and install it for me without any issues

### Steps to reproduce

Create 1.12.2 Forge instance
Search curseforge for MinersAdvantage
No valid version found for a mod

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
What's wrong with CurseForge?
CurseForge added a new option to block third party clients like Prism Launcher from accessing mod files, and they started to enforce this option lately. We can't allow you to download those mods directly from CurseForge because of this. However, Prism Launcher offers a workaround to enable the downloading of these mods, by allowing you to download these mods from your browser and automatically importing them into the instance. We highly encourage asking authors that opted out of client downloads to stop doing so.

**Comment by ghost** [comment]
PolyMC have ability to download this mod

**Comment by Trial97** [comment]
From what I know PolyMc uses Curseforge API key and it is against Curseforge TOS
