### ISSUE TITLE
Wrong Version of Mod is Downloaded when multiple builds are available

### ISSUE THREAD

**Issue by Nicolas-GE** [PrismLauncher/PrismLauncher#2538]
### Operating System

Windows

### Version of Prism Launcher

7.2

### Version of Qt

6.5.1

### Description of bug

this issues happened to me when i made a 1.20.1 instance with the dynamic-fps mod

when i selected version 3.4.3, which has builds for all versions of 1.20.x, it downloads the 1.20.5-1.20.6 version instead of the 1.20-1.20.4 version

### Steps to reproduce

make a 1.20-1.20.4 instance (i made a 1.20.1 instance)
add a mod with multiple builds for one version (for example dynamic fps which has 3.4.3 for 20-.4 and .5-.6)

### Suspected cause

i think the launcher downloads the latest build of a mod for that version, so if one mod version has multiple builds made for multiple game versions, it only downloads the latest one which can cause errors

a possible fix would be to have an additional field to let the user choose which sub-version is the correct one, auto-selected to be the closest match to the instance's game version

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Nope 3.4.3 is also marked for 1.20.1
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/90a860f6-df15-4919-a104-438dffaa0dde)

**Comment by maskersss** [comment]
i think you misunderstood their point, they were saying that prism downloaded the version for 1.20.5-.6 despite there existing a 1.20.1 version and the instance being on 1.20.1
i couldn't replicate it though, could maybe be an old bug that was already fixed by now?
![image](https://github.com/PrismLauncher/PrismLauncher/assets/97827489/22757ebc-5f48-4727-ada5-4150c88f5271)

**Comment by Trial97** [comment]
You did not get my point either: prism will always download the latest version that is marked for the loader and mc version selected.
It did download the correct file as on the provider side it was marked as compatible with 1.20.1
So basically this needs to be changed on the provider not on prism.

**Comment by Trial97** [comment]
also related to this issue: It is being reported on 7.2 so there is no reason even to consider it (please always update to the latest stable version before reporting an issue)

**Comment by maskersss** [comment]
![image](https://github.com/PrismLauncher/PrismLauncher/assets/97827489/f89f5333-2783-406a-9852-b9c7b749c111)
as i understood, they were saying that prism downloaded the red version instead of the blue one despite the fact that the red version isn't marked for the mc version of the instance (1.20.1)

**Comment by Trial97** [comment]
And again I can't reproduce it on the latest nightly and the author mentioned that it was using 7.2, so there are still no dice.

**Comment by Nicolas-GE** [comment]
can confirm that this isn't an issue on 8.3, it correctly finds the 1.20.0 instead of 1.20.5, i forgot that prism didn't have auto-updates or never did them if it did
