### ISSUE TITLE
Cleanroom Loader Support

### ISSUE THREAD

**Issue by roidrole** [PrismLauncher/PrismLauncher#2551]
### Role

I make and play modpacks

### Suggestion

I want to be able to choose the CleanroomMC loader for Minecraft 1.12.2 profiles instead of forge

### Benefit

Cleanroom is compatible with Java 21, which greatly increases performance, but is currently annoying to set up because it is an alternative to forge. If Prism would let me choose it, the experience would be better for me and my playmates

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

[CleanroomMC](https://github.com/CleanroomMC/Cleanroom) is compatible with practically all forge mods, so the mod lists are the same. Although it's currently in alpha state, it is still very playable with a lot of mods/packs

**Comment by Ryex** [comment]
From the looks of things Cleanroom has already done the work for you to include the launcher with custom components. considering this laucher is meant to support one specific version of minecraft. it makes much more sense to have users use the custom component system.

Import the MultiMC instance they have in the assests on their [releases](https://github.com/CleanroomMC/Cleanroom/releases)
or follow the instructions they have in the readme

**Comment by mazunki** [comment]
I would also like this feature.

While it's not exactly hard to install something under Cleanroom (their instructions are pretty clear and mechanic), it's kind of tedious and could be automatized. The main feature which we could get it is modpack updates being seamless.

Generally, installing a package under cleanroom involves:
- Installing a fresh Cleanroom instance (download + import)
- Installing a temporary instance of the modpack you want through normal Prismlauncher means
- Launch Cleanroom to build up some necessary files
- Copy `.minecraft/*` from modpack into `./minecraft/` of Cleanroom.
- Remove MixinBooter and sometimes some other mods
- Delete the modpack instance since it's no longer useful
- Fix potential Cleanroom instance name, icon, etc

Through these steps, we lose meaningful information like the automated modpack icon/logo, version updates, and instance name. Of course, one can do this manually, but having this process stream through the Launcher would be great QoL.

Is this something which would be accepted as a PR?

**Comment by mer2329** [comment]
i would also like to have direct support for cleanroom. 
for large modpacks its AMAZING. but migrating your packs to it is a hassle. and usually its easier to do a fresh cleanroom setup for the packs. being able to replace forge with cleanroom on the version page would make the first step things MUCH easier.

**Comment by thedarkcolour** [comment]
If someone submits a PR for this feature, is there a chance it could get accepted? I understand the Prism devs not wanting to implement this behavior themselves, but was hoping someone else's efforts would be considered.

**Comment by Rongmario** [comment]
> From the looks of things Cleanroom has already done the work for you to include the launcher with custom components. considering this laucher is meant to support one specific version of minecraft. it makes much more sense to have users use the custom component system.

Reopen this issue, not sure why it's closed as "resolved".
