### ISSUE TITLE
Add the ability to specify which filetypes get shell association

### ISSUE THREAD

**Issue by hyprfixation** [PrismLauncher/PrismLauncher#2666]
### Role

I play modded Minecraft.

### Suggestion

installer do explorer thing on window

### Benefit

just a QOL tweak because of how i normally use windows

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Add the ability to specify which filetypes get shell association in the launcher's installer, why would i only open my zip files in prism launcher? you get the point this is a nice QOL tweak, and it would be nice if you could change this on existing installs further

**Comment by hyprfixation** [comment]
idk why i cut off the further i'm confused

**Comment by Trial97** [comment]
This is because Prism registered itself as a possible zip opener.
This will not be fixed in prism as this can already be achieved in both Linux and windows explores:
- right click on a zip file
- open with
- select default application
- select the application that you want to use to open the zip by default
- done
