### ISSUE TITLE
Modpack version published on Curseforge not available

### ISSUE THREAD

**Issue by mainrs** [PrismLauncher/PrismLauncher#2670]
### Operating System

Linux

### Version of Prism Launcher

8.4

### Version of Qt

6.7.2

### Description of bug

[Material Energy 5](https://www.curseforge.com/minecraft/modpacks/material-energy-5-entity) has released versions on Curseforge. However, the pack cannot be installed.

### Steps to reproduce

Via `Add Instance > Curseforge`, search for `Material Energy` and select the fifth installment called `Material Energy^5: Entity`.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
What's wrong with CurseForge?
CurseForge added a new option to block third party clients like Prism Launcher from accessing mod files, and they started to enforce this option lately. We can't allow you to download those mods directly from CurseForge because of this. However, Prism Launcher offers a workaround to enable the downloading of these mods, by allowing you to download these mods from your browser and automatically importing them into the instance. We highly encourage asking authors that opted out of client downloads to stop doing so.

**Comment by mainrs** [comment]
@Trial97  I have seen that when mod authors have blocked it. Then I can download the files using my browser and PrismLauncher picks them up. This is what you describe.

My issue is about a mod pack. PrismLauncher does not find/provide me with any mod pack version. I cannot download the pack.

![image](https://github.com/user-attachments/assets/afe35522-d26c-405b-81d2-df5e194e540a)

**Comment by Trial97** [comment]
It is the same stuff with modpacks. The third part block is not limited only to mods.

**Comment by mainrs** [comment]
> It is the same stuff with modpacks. The third part block is not limited only to mods.

Ah, OK! I wasn't aware of that. Thank you for clarifying!
