### ISSUE TITLE
error code number 2

### ISSUE THREAD

**Issue by fooooooy** [PrismLauncher/PrismLauncher#2681]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.6.3

### Description of bug

I made a build for 130+ mods and for optimization I also added mods for optimization, but after them now minecraft does not start at all with error code number 2

### Steps to reproduce

Click the start button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Thank you for bringing this to our attention. After reviewing the details, we have determined that this issue is unrelated to the launcher. If you need any more help with this kind of issue, we recommend contacting our community on Discord:https://prismlauncher.org/discord.

We appreciate your understanding and cooperation.

**Comment by Samalando** [comment]
The game is crashing most likely because of an incompatibility. It would be more preferable if you join the discord server (https://prismlauncher.org/discord) and send your logs
