### ISSUE TITLE
Error code -1

### ISSUE THREAD

**Issue by fooooooy** [PrismLauncher/PrismLauncher#2727]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

https://mclo.gs/1wjTeNT

### Steps to reproduce

* Click the "run" button
* Start creating a world
* The game crashes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Not a launcher issue try asking for the discord: https://prismlauncher.org/discord

**Comment by fooooooy** [comment]
I've been trying for 2 weeks, no one answered me, I decided to go here. Can you still help me somehow?

**Comment by Trial97** [comment]
I will invoke rule 10 of the discord server: ` All support is done voluntarily. People might not know how to fix your problem, if no one has responded to your request for a long time.` 
And to answer your question, because your issue is unrelated to the launcher I don't know how to solve it, so I can't help you.
Here is something you can try:
#Binary Search - A method of finding problems with mods
The binary search is a way of finding a faulty thing amongst a lot of other things, without having to remove the things one-by-one. This is useful for finding a broken mod among hundreds of mods, without having to spend time testing the mods one-by-one.

The procedure is simple:

   1. Remove half of the existing things, and put them aside.
   2. Run the program / game.
   3. Does the issue still exist?
   4. If YES: Repeat from step 1 with the current things.
   5. IF NO: Swap out the current things with the ones set aside, and repeat from step 1.
   6. Repeat this process until the problematic thing/s have been found.


Credit to the Quilt Community discord and the Forge Discord for these instructions.

P.S. If you go with that method do a world backup
