### ISSUE TITLE
Add support for Android devices

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#276]
### Role

I play Minecraft Java on Android

### Suggestion

Add support for running the launcher on Android phones

### Benefit

So that I can use all my current instances on my phone

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

There are already ways to play [Minecraft Java on Android](https://github.com/PojavLauncherTeam/PojavLauncher) but the launchers are all kinda bad. So it would be cool if I can use just one launcher for my PC, Android phone and Steam Deck

**Comment by code-irisnk** [comment]
This would honestly only make sense for a Quest 2 or standalone VR setups that are based on Android. 

I seriously doubt most Android phones would be able to run Minecraft Java (from previous experience with PoJav Launcher). 

This would need a lot of work on the launcher itself to add touch controls and generally just make it an Android app which I highly doubt will happen since the launcher is almost entirely written on C/C++ and based on QT.

**Comment by TayouVR** [comment]
I think this could happen eventually, but definitely not short term. Currently Prism is based on the aging Qt Widgets ecosystem for UI, to work well on mobile it'd be best to switch to QML or Kirigami... which is possible, but not likely (at least short term). As for actually running MC, given Pojav can do it I'm sure we could figure out how to do it from Prism too.

I would love Prism on mobile. Would be very nice!

**Comment by ghost** [comment]
This would need an RFC thread.

**Comment by Scrumplex** [comment]
Unlikely. The UI won't work on a touch screen and we would also need to get Java running. Maybe just use Pojav
