### ISSUE TITLE
Can't rename overrides folder

### ISSUE THREAD

**Issue by RedSatiin** [PrismLauncher/PrismLauncher#2762]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

An instance of my requested modpack should have been installed properly.  It did not. instead, I got "Error while creating new instance: Could not rename the overrides folder: overrides"

### Steps to reproduce

Click Add Instance
Click Curseforge
In the search bar type Sea
Attempt to add Seaopilis: Submerged
I have attempted Seaopolis, DawnCraft, All The Mods 9.. There are tons more and I have no clue how to fix this.. Please help me.

### Suspected cause

No Idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This happens because the files inside the overrides folder are open in another program(usually an antivirus, recommend disabling it when you download a modpack).
This was fixed in the nightly version and will be released in 9.0, see the duplicate issue closed: https://github.com/PrismLauncher/PrismLauncher/issues/1629.

If you do not want to disable the antivirus or that doesn't work give the nightly version a try and only report back if that version doesn't work:

You can download unstable builds [here](https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop).
    
Caution
    Unstable builds have more bugs and are therefore more likely to break! By using the latest commit you are using software which has not been properly tested. For this reason we recommend using Portable or AppImage builds, or least making a backup.

**Comment by RedSatiin** [comment]
This did not fix the problem, It's worked on some modpacks but not all of them I still have issues with the same error for Seaopolis but a couple of others work.. I'm still trying to get Seaopolis.

I ended all anti-virus processes as I could, even turned off the AV, and restarted PC, which allowed a couple. 
I went to each folder I could find and turned off read-only. I could not find the overrides folder.

I don't know what version of the night thing I'm supposed to get I tried the x86 64 but it has some flakpack files or something like that and when I click it asks what to open it with.. I don't know.. and all the others say Debug.. no idea what that's for..
