### ISSUE TITLE
Curseforge modpacks not showing correctly

### ISSUE THREAD

**Issue by adamcirillo** [PrismLauncher/PrismLauncher#2772]
### Operating System

Windows

### Version of Prism Launcher

8.4

### Version of Qt

QT 6.7.1

### Description of bug

curseforge modpacks show up in the list but there is no downloads, can see on the curseforge website and client have attached screenshots of some examples

![image](https://github.com/user-attachments/assets/71425d22-2f36-4600-9f5d-8112805b5102)
![image](https://github.com/user-attachments/assets/7c04eb90-9cac-4f23-a6a2-3681daecb308)
![image](https://github.com/user-attachments/assets/9cea5bbe-6687-4672-88cf-0a4c8d12b8e9)
![image](https://github.com/user-attachments/assets/e883d1bf-9c58-40e0-8f3d-fe31c4d4959f)
![image](https://github.com/user-attachments/assets/0b686c3c-976d-470f-9866-bb47eb083789)
![image](https://github.com/user-attachments/assets/97e45072-a73a-48ca-b401-69554cc12108)

### Steps to reproduce

search for the modpack in prism and you will see no version available

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Curse forge blocks third party launchers

**Comment by pwaller** [comment]
Is there a workaround, or an umbrella ticket, or is this documented somewhere? It's confusing as a user as I can't efficiently find information about what's supposed to happen. Is it just for informational purposes or is there a way to run this mod under prism launcher if you take some manual steps?

**Comment by pwaller** [comment]
To answer my own question, it looks like you can:
1. Download the modpack from curseforce
2.  'create instance'
3. Select the downloaded modpack file under 'import'
4. Download any remaining pieces manually as the UI guides you.

**Comment by Trial97** [comment]
What's wrong with CurseForge?
CurseForge added a new option to block third party clients like Prism Launcher from accessing mod files, and they started to enforce this option lately. We can't allow you to download those mods directly from CurseForge because of this. However, Prism Launcher offers a workaround to enable the downloading of these mods, by allowing you to download these mods from your browser and automatically importing them into the instance. We highly encourage asking authors that opted out of client downloads to stop doing so.

This applies to modpacks also and that is the correct approach for this( manually downloading the pack)

**Comment by pwaller** [comment]
:+1:, what you've described just wasn't clear as a naive user trying to use the app. And when you said "Curse forge blocks third party launchers" above, it wasn't clear if it was possible to work around this at all.
