### ISSUE TITLE
Not recognizing a modpack on curseforge

### ISSUE THREAD

**Issue by GrimTheWanderer** [PrismLauncher/PrismLauncher#2847]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

QT 6.6.3

### Description of bug

The launcher is reporting that there is no version available to download when one exists, nor does it recognize the download URL for the file. When entering the download URL through the import utility, a "one or more subtasks failed" error message pops up. Can import the zip file downloaded manually from curseforge.
URL of the pack: https://www.curseforge.com/minecraft/modpacks/createa-colony
![image](https://github.com/user-attachments/assets/fffb8780-a9d4-4bdd-8eb6-4216964fce36)

### Steps to reproduce

Add instance -> Curseforge -> search: create'a colony

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
What's wrong with CurseForge?
CurseForge added a new option to block third party clients like Prism Launcher from accessing mod files, and they started to enforce this option lately. We can't allow you to download those mods directly from CurseForge because of this. However, Prism Launcher offers a workaround to enable the downloading of these mods, by allowing you to download these mods from your browser and automatically importing them into the instance. We highly encourage asking authors that opted out of client downloads to stop doing so.

**Comment by Trial97** [comment]
Oh yeah, fix: manually download the zip folder from the curseforge then import that into prism

**Comment by GrimTheWanderer** [comment]
The issue here is not recognizing the modpack download at all. I have encountered this with no other packs, listing no version available, which leads me to believe there is a specific bug occurring here, other than the changes to third party downloads being blocked. Does the third party blocking include modpacks, not just mods individually? If so, maybe change the language in the boilerplate response to signify this.

**Comment by Trial97** [comment]
Sorry copied the boilerplate from discord server.
But yes the block applies to all projects on curseforge
