### ISSUE TITLE
If the path contains Japanese characters, JavaCheck.jar cannot be executed.

### ISSUE THREAD

**Issue by marrrrrrme6** [PrismLauncher/PrismLauncher#2892]
### Operating System

Windows

### Version of Prism Launcher

Prism launcher 8.4

### Version of Qt

6.6.3

### Description of bug

If the path to JavaCheck.jar contains Japanese characters, JavaCheck.jar cannot be executed.

### Steps to reproduce

This error occurs when you click Preferences -> Java -> Auto Detect.
The thing hidden in black is the username.
And the username is in Japanese.
![image](https://github.com/user-attachments/assets/c6bc8dd1-6af2-46de-8031-01c5c7fde40d)

### Suspected cause

The path contains Japanese characters.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This sounds like: https://github.com/PrismLauncher/PrismLauncher/issues/131 and it should be fixed(also using that version I'm not able to reproduce it)
Are you sure on 8.4?
Can you ensure that the path to JavaCheck exist and is accessible(readable by the current user)?
Can you provide any Prism logs?

**Comment by marrrrrrme6** [comment]
It's definitely 8.4.
And I can call it from cmd, so I have permission to execute it.
When I installed it directly in C:\, no errors were displayed.
[PrismLauncher-0.log](https://github.com/user-attachments/files/17271156/PrismLauncher-0.log)

**Comment by marrrrrrme6** [comment]
Oh, I forgot to mention something important.
The Japanese text was garbled.

**Comment by Ryex** [comment]
interesting.
try running the java-checker jar manually using the same command Prism does. see what the fail reason is.

in your case that would mean
```
"C:/Users/検証ユーザ/AppData/Local/Programs/Microsoft VS Code/bin/javaw.exe" -jar "C:/Users/検証ユーザ/Downloads/PrismLauncher/jars/JavaCheck.jar"
```

**Comment by marrrrrrme6** [comment]
The command presented could not be executed, so I changed it to this:
```
java.exe -jar "C:/Users/検証ユーザ/Downloads/PrismLauncher/jars/JavaCheck.jar"
```
And when I called it from cmd, no errors occurred.
The result was displayed like this:
```
os.arch=amd64
java.version=21.0.4
java.vendor=Oracle Corporation
```

**Comment by Ryex** [comment]
If the command in my comment could not be exacted as presented that means that your java is set up incorrectly in prism. That is the command prism is trying to run in the logs you provided.

**Comment by Trial97** [comment]
I know is a long shot but I have no info on what is the exact java that fails. Can you try running the JavaChecker with the following:
- "C:/Program Files/Java/jre1.8.0_421/bin/javaw.exe"
- "C:/Program Files/Java/jre8/bin/javaw.exe"
- "C:/Program Files/Java/jre7/bin/javaw.exe"
- "C:/Program Files/Java/jre6/bin/javaw.exe"
- "C:/Program Files/Java/jdk-21/bin/javaw.exe"
- "C:/Program Files (x86)/Java/jre8/bin/javaw.exe"
- "C:/Program Files (x86)/Java/jre7/bin/javaw.exe"
- "C:/Program Files (x86)/Java/jre6/bin/javaw.exe"
- "javaw"
- "C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe"
- "C:/Program Files (x86)/Common Files/Oracle/Java/java8path/javaw.exe"
- "C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe"
- "C:/Windows/system32/javaw.exe"
- "C:/Windows/javaw.exe"
- "C:/Windows/System32/Wbem/javaw.exe"
- "C:/Windows/System32/WindowsPowerShell/v1.0//javaw.exe"
- "C:/Windows/System32/OpenSSH//javaw.exe"
- "C:/Program Files/dotnet//javaw.exe"
- "C:/Program Files/Git/cmd/javaw.exe"
- "C:/Users/検証ユーザ/AppData/Local/Microsoft/WindowsApps/javaw.exe"
- "C:/Users/検証ユーザ/Downloads/busybox/javaw.exe"

If it doesn't start because the file doesn't exist just ignore it(this is a list generated by prism with possible java locations). Report back only the ones that creates that dialog.

**Comment by marrrrrrme6** [comment]
Is it normal that nothing shows up when I start it with javaw?

**Comment by marrrrrrme6** [comment]
> * "C:/Program Files/Java/jre1.8.0_421/bin/javaw.exe"
> * "C:/Program Files/Java/jdk-21/bin/javaw.exe"
> * "javaw"
> * "C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe"
> * "C:/Program Files (x86)/Common Files/Oracle/Java/java8path/javaw.exe"
> * "C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe"

For now, we'll assume that it's normal for nothing to be displayed when you run javaw.
What remains is the java that existed.
Of these, the only one that caused an error was "C:/Program Files (x86)/Common Files/Oracle/Java/java8path/javaw.exe".

**Comment by Trial97** [comment]
> Is it normal that nothing shows up when I start it with javaw?

The command `<path to java> -jar "C:/Users/検証ユーザ/Downloads/PrismLauncher/jars/JavaCheck.jar" should print in the terminal some basic information about the current OS.



> Of these, the only one that caused an error was "C:/Program Files (x86)/Common Files/Oracle/Java/java8path/javaw.exe".

Do you get the same dialog that you would get with prism?
If yes try to temporarily rename the `"C:/Program Files (x86)/Common Files/Oracle/Java/java8path/javaw.exe"` to something else, then open Prism autodetect and check if you get the same error dialog? If you do not get it in Prism after rename then is not a issue with the launcher but the java.

**Comment by marrrrrrme6** [comment]
java8path was the problem.
Sorry.
