### ISSUE TITLE
App not starting

### ISSUE THREAD

**Issue by Tasty-Bacon** [PrismLauncher/PrismLauncher#2983]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.7.3

### Description of bug

I can't start the Launcher normally with a doubleclick no matter if its in the file explorer or from desktop or in taskbar.
So far it only starts when i run it as an admin.
I've tried reinstalling already

### Steps to reproduce

Item is pinned in taskbar and clicking it -> loading symbol next to mouse but doesnt start, no task in taskmanager visible either
Item from folder in file explorer and clicking it -> loading symbol but doesnt start either
right click -> run as admin -> works normally

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Because you opened prism as admin you messed up the root folder permissions.
The root directory is at `%APPDATA%/PrismLauncher`.
Please fix the permissions on that folder and subfolders.

Here is a tutorial on how to change permissions:(first Google link)https://www.thewindowsclub.com/change-files-and-folders-permissions-in-windows-10

**Comment by Tasty-Bacon** [comment]
Doesn't work. Even after reinstalling and changing the folder permissions before opening it it doesn't work. Same issue is with the Portable version.
Every entry in the permissions has "Full control" written in access, and it applies to "that folder, subfolders and files"
