### ISSUE TITLE
Prism launcher (symlinking) CRASHES

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [PrismLauncher/PrismLauncher#3004]
### Operating System

Linux

### Version of Prism Launcher

Prism launcher 8.4

### Version of Qt

Qt 5.15.9

### Description of bug

Symlinking minecraft world save directory leads to a crash. I have prism launcher set up so the minecraft world folder is symlinked on both my main device and my steam deck, then syncthing transfers them, however prism launcher is crashing when i tries to read out of .minecraft/saves just because its a symlink.
Error log:
https://pastebin.com/T850dCfS

Main error bit:
`java.io.UncheckedIOException: java.nio.file.FileAlreadyExistsException: /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/DeckCraft/.minecraft/saves`

### Steps to reproduce

1. Removed your save folder for any instance.
2. Create a symlink (the save folder should be linked to another location/folder)

Try and start Minecraft

(maybe it has something to do with syncing the files using a tool like synching, but I would try just a basic symlink)Remove

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is not a launcher issue:the minecraft instance fails because of the symlink

**Comment by MestreLion** [comment]
Actually, this is likely a Prism Launcher issue indeed... as it didn't happen with MultiMC launcher circa MC 1.17

**Comment by MestreLion** [comment]
Oh, never mind, I've just found https://www.reddit.com/r/Minecraft/comments/13v5xuv/banning_symlinks_is_pretty_messed_up_mojang/ , so this is indeed an (intentional) Minecraft limitation since 1.20

**Comment by MestreLion** [comment]
Digging up further.. this is actually a **Flatpak** issue! They way it sandboxes applications, for manually-created symlinks to work you must run Prism as `flatpak run --filesystem=<SYMLINK_TARGET> org.prismlauncher.PrismLauncher`. You need to add one `--filesystem` options per each unique symlink target.

If several symlinks have the same target (for example, when creating a symlink to a common `saves` folder in several instances, you only have to specify it once.

Example:
```
cd ~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances
rmdir myinstance{A,B,C}/minecraft/saves
ln -s ~/mysaves  myinstanceA/minecraft/saves
ln -s ~/mysaves  myinstanceB/minecraft/saves
ln -s ~/mysaves  myinstanceC/minecraft/saves
rmdir myinstance{A,C}/minecraft/resourcepacks
ln -s ~/mypacks  myinstanceA/minecraft/resourcepacks
ln -s ~/mypacks  myinstanceC/minecraft/resourcepacks

flatpak run --filesystem=~/mysaves --filesystem=~/mypacks org.prismlauncher.PrismLauncher
```

Since Flatpak is the recommended packaging format for Prism Launcher, maybe add a note about this in the README / FAQ?

**Comment by MestreLion** [comment]
... or use [Flatseal](https://github.com/tchx84/flatseal)
