### ISSUE TITLE
prevents sleepmode in linux mint 22

### ISSUE THREAD

**Issue by mcredstoner** [PrismLauncher/PrismLauncher#3089]
.

**Comment by Trial97** [comment]
Not a prism issue.

**Comment by mcredstoner** [comment]
Do you know what program's fault it is then?

**Comment by Trial97** [comment]
From the modpack you are playing to the list of programs that you have.
My guess is related to Nvidia: because it is overused, it may block the suspension until it is cooled(that is a wild guess).
But this is a guess. As you mentioned, this doesn't happen with all the mod packs but only with the more demanding ones.
Prism doesn't inhibit the sleep/suspend functionality.

**Comment by mcredstoner** [comment]
I can understand where the idea of Nvidia prohibiting it but then it's also confusing that I stopped it yesterday a few hours before I tried to suspend the system. I will look further into the problem and thanks for the prognoses you gave me.
