### ISSUE TITLE
Support for installing Magic Mojo Mod Loader (M3L)

### ISSUE THREAD

**Issue by muzikbike** [PrismLauncher/PrismLauncher#3110]
### Role

Messing with mods on legacy versions

### Suggestion

There should be some way to install this mod loader with minimal, effort, like can be done with Forge and Fabric

### Benefit

The current tool is only intended for use with the official Mojang launcher and does not seem to work anymore since it's a decade old at this point.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

see also: #3097 and related

Official site: https://www.cuchazinteractive.com/minecraft/m3l/

Code archive: https://web.archive.org/web/20200630225837/https://bitbucket.org/cuchaz/m3l/get/5e1f7cf76578.zip

I don't think this should be available at the exact same level as the forge, fabric and liteloader buttons, but should nonetheless be accessible somewhere, perhaps in some sort of "Other Loaders" section.

**Comment by Samalando** [comment]
This itself has not been said but it is on the same grounds as orthrine, legacy fabric and other old Minecraft version loaders. The rule of thumb is that if enough people want it, it will be added

**Comment by Stein-N** [comment]
![grafik](https://github.com/user-attachments/assets/9d8a4931-5f23-48b0-b333-a33227cfced8) would say this feature can be scrapped

**Comment by TheKodeToad** [comment]
If there's a maintained fork, maybe

**Comment by muzikbike** [comment]
Is that a requirement? LiteLoader isn't maintained either as far as I'm aware, yet can be installed just fine.

**Comment by Samalando** [comment]
That's because there is a high amount of want for it. I've never heard of magic mojo mod loader before today so unless more people want it, support might be added

**Comment by Stein-N** [comment]
Also the difference between M3L and Lite loader is, that Lite loader Mod can be downloaded from Curseforge and Modrinth. Like Samalando said the M3L is not really known and I would assume that there is no index site for Mods written specifically for M3L.

**Comment by Niko-sk2x** [comment]
To even explain what M3L even was because anyone reading this probably has no idea:

The only one mod that has ever been made for M3L is TallWorldsMod. All the code in that mod loader existed only to serve the needs of that one mod and nothing else. The only APIs in it were the core parts of TallWorldsMod itself. I was one of the devs of TWM, and can confirm there is zero point adding this. The only version of tall worlds mod ever released was for a beta for MC 1.8.3 and even that barely ran. [This commit](https://github.com/OpenCubicChunks/CubicChunks/tree/cf3432e768c14433f3345d914bcd97f2d5cde2c6) is a 1.8.9 port to regular forge, compatible with the same world saves and much ~more stable~ less unstable. If there is a demand for it, I could probably still compile and publish it.
