### ISSUE TITLE
App Crashes when installing resource packs

### ISSUE THREAD

**Issue by MiroTheMouse** [PrismLauncher/PrismLauncher#3163]
### Version of Prism Launcher

9.1

### Version of Qt

6.8

### Description of bug

When i Finish choosing wich resource packs to download it's just completly crashes

### Steps to reproduce

try adding a version compatibility feature for not to install the wrong version

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sage-Axolotl** [comment]
I have also Experienced this issue. I have attached some log files.
[PrismLauncher-1.log](https://github.com/user-attachments/files/18013286/PrismLauncher-1.log)
[PrismLauncher-2.log](https://github.com/user-attachments/files/18013287/PrismLauncher-2.log)
[PrismLauncher-3.log](https://github.com/user-attachments/files/18013288/PrismLauncher-3.log)

**Comment by Trial97** [comment]
This should be fixed in nightly: 
Where can I download unstable builds of Prism Launcher?
You can download unstable builds [here](https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop).

    :warning: Caution
    Unstable builds have more bugs and are therefore more likely to break! By using the latest commit you are using software which has not been properly tested. For this reason we recommend using Portable or AppImage builds, or least making a backup.

If you can reproduce it nightly then please using: https://github.com/Trial97/prism_gdb 
- download and extract this portable version:https://github.com/Trial97/prism_gdb/blob/master/PrismLauncher-Windows-MinGW-w64-Portable-9.2.zip
- Now start prism using the gdbprismlauncher.bat file(the extension may be missing); do not touch the opened command prompt(black thing with text)
- Try to reproduce the crash;if the application is stuck leave it a few minutes(it takes a while to generate all the backtrace)
- Share with develeopers the `gdbcrash.log` file generated on same level as the gdbprismlauncher.bat

I will close this until a `gdbcrash.log` is provided
