### ISSUE TITLE
Prism Launcher us crashing when downloading 20 ore more mods

### ISSUE THREAD

**Issue by KingPanther2006** [PrismLauncher/PrismLauncher#3226]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

QT 6.7.3

### Description of bug

When i want to Download 20 ore more mods at the same time, the launcher will crash!

### Steps to reproduce

Create a new instance with forge or fabric, then go to mods and select 20 ore more mods from the Downloader and Download all off them at the same time. The launcher will crash and the Downloaded files can be corrupted

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This should be fixed in nightly: 
Where can I download unstable builds of Prism Launcher?
You can download unstable builds [here](https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop).

    :warning: Caution
    Unstable builds have more bugs and are therefore more likely to break! By using the latest commit you are using software which has not been properly tested. For this reason we recommend using Portable or AppImage builds, or least making a backup.

If you can reproduce it nightly then please using: https://github.com/Trial97/prism_gdb 
- download and extract this portable version:https://github.com/Trial97/prism_gdb/blob/master/PrismLauncher-Windows-MinGW-w64-Portable-9.2.zip
- Now start prism using the gdbprismlauncher.bat file(the extension may be missing); do not touch the opened command prompt(black thing with text)
- Try to reproduce the crash;if the application is stuck leave it a few minutes(it takes a while to generate all the backtrace)
- Share with develeopers the `gdbcrash.log` file generated on same level as the gdbprismlauncher.bat

I will close this until a `gdbcrash.log` is provided
