### ISSUE TITLE
The launcher doesn't see the appropriate version of the mod

### ISSUE THREAD

**Issue by Redls07** [PrismLauncher/PrismLauncher#3234]
### Operating System

Windows

### Version of Prism Launcher

9.1

### Version of Qt

6.7.3

### Description of bug

For some reason, the launcher does not see the appropriate version of the mod, although it is available. In addition, for some reason the search does not display the mod at the beginning, and the mod has to be searched much lower.

### Steps to reproduce

This can be seen in the example of the Better Fog mod with Curseforge

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Redls07** [comment]
https://github.com/user-attachments/assets/4af288f4-f42e-4219-8b9f-521372a1e6ad

**Comment by Trial97** [comment]
What's wrong with CurseForge?
CurseForge added a new option to block third party clients like Prism Launcher from accessing mod files, and they started to enforce this option lately. We can't allow you to download those mods directly from CurseForge because of this. However, Prism Launcher offers a workaround to enable the downloading of these mods, by allowing you to download these mods from your browser and automatically importing them into the instance. We highly encourage asking authors that opted out of client downloads to stop doing so.

**Comment by Redls07** [comment]
@Trial97 Okay, but then what about the search? Is it normal that the mod doesn't appear at the beginning? When searching on Curseforge itself, everything is fine

**Comment by Trial97** [comment]
Yes is normal, curse forge is no third-party
