### ISSUE TITLE
Improve the skin/cape selection UI.

### ISSUE THREAD

**Issue by AyeTSG** [PrismLauncher/PrismLauncher#330]
### Role

I manage my skins and capes using Prism Launcher.

### Suggestion

I want the skin upload and cape management UI to be more intuitive.

### Benefit

This would provide a better experience when managing skins and capes using Prism Launcher

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Prism Launcher should show a preview of the skin, and cape selected, when editing an account's skin/cape data using Prism Launcher. This feature occurs in the official launcher, but is absent from Prism. Currently, when selecting a cape, only the cape's name is shown, and no such preview. There is also no such preview with skins. This requires the user to go into the game just to see their changes. I feel that Prism Launcher should overhaul the skin/cape selection UI to better show the changes the user is making.

#1534 & #311: The launcher should also allow multiple skins to be saved

**Comment by ja2ui0** [comment]
Agree 100%.

[Skin Swapper](https://www.curseforge.com/minecraft/mc-mods/skin-swapper) has a nice enough UI for this, but requires that you be launched into a session to use. It's a good workaround for now, but since skins are global and session independent, a visual UI update for Prism Launcher itself would be more appropriate.

If anyone decides to work on this, these features would all be cool:

- load skins from a local file
- push updated skins upstream to MS
- pull skins by username from MS
- visualize skins from the launcher
- select and visualize capes from the launcher

I don't use any offline accounts myself, but a nice "bonus points" feature that fits with the overarching goals of a modded MC launcher might be ability to select a skin server (or multiple) to update. Players can have different skins for servers that operate offline or simply use alternate skin servers, as in with [HD Skins](https://modrinth.com/mod/hd-skins) in Java.
