### ISSUE TITLE
Doesn't Respect System Theme

### ISSUE THREAD

**Issue by Ari-43** [PrismLauncher/PrismLauncher#49]
### Operating System

Windows

### Version of PolyMC

5.0-develop

### Version of Qt

Qt 6.4.0

### Description of bug

PrismLauncher doesn't respect the system theme when `Settings -> Launcher -> User Interface -> Colors` is set to `System`

This is on Windows 10 21H1

### Steps to reproduce

1. Set the Windows system theme to dark via Windows settings
2. Open PrismLauncher
3. Click `Settings`
4. Go to the `Launcher` section of the Settings window (if not already there)
5. Go to the `User Interface` tab of the Launcher settings
6. Set `Colors` to `System` (if it isn't already)
7. Note that PrismLauncher is still in light mode, even after it's restarted

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
dark theme? qt doesn't support it yet

**Comment by Ari-43** [comment]
Oh, I thought I remembered it working in MultiMC, but it appears I was wrong. Closing this issue...

**Comment by TayouVR** [comment]
currently Qt (and therefore the launcher) use the windows theme colors from windows' themeing engine introduced in winXP. In order to actually customize those old school themes you can mod windows and install custom themes, a simple google search for "windows install custom theme" should point you in the right direction if you wish to go that route. (I can recommend the Penumbra10 theme from deviantart)

But yeah, in a later Qt version proper dark mode support should be added for windows. We will hopefully have that whenever Qt adds it.

**Comment by Ari-43** [comment]
Ok, thank you for the info! 
Is it possible for the option to be greyed out or a message displayed to prevent other users from being confused by the same issue?

**Comment by TayouVR** [comment]
that could be done, though I don't think its relevant enough to spend dev time on doing that, especially right now...

**Comment by Ari-43** [comment]
Yes, of course, there are much more pressing matters.
