### ISSUE TITLE
.minecraft/versions support?

### ISSUE THREAD

**Issue by catvin82** [PrismLauncher/PrismLauncher#539]
### Role

I play modded and hack w/ permission on servers/singleplayer

### Suggestion

I want prism to have some sort of .minecraft/versions/ implemetation

### Benefit

So you can use minecraft clients that don't use modder platforms.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

i searched up "versions" and nothing relating came up.

**Comment by Xetaxheb** [comment]
what would the point be? what exactly is your use case? what are you trying to install? you can already jarmod or replace the jar in **version tab**.

**Comment by TheKodeToad** [comment]
In many cases these version files contain other things besides simply a jar replacement.

**Comment by catvin82** [comment]
I don't want to encorage hacking on servers without permisson, but a lot of clients (sigma client shown) have these 2 files and launch using the .versions folder.  
![image](https://user-images.githubusercontent.com/96541972/205465491-f94c6f9f-d4e6-4690-b59a-76cbceea4e48.png)

**Comment by Xetaxheb** [comment]
"hacking _on servers_" is irrelevant, people will find a way and as a concern ignores that it's perfectly doable on forge/fabric identically...

the question was what is your use case (in a technical way) and what are you trying to install? 

ignoring sigma5 since it's been discontinued .. what client are you trying to install that isn't forge/fabric, can't simply use the "replace minecraft jar" on, and doesn't use its own native code/launcher that would be incompatible anyway?

**Comment by catvin82** [comment]
I didn't know you could replace jar, I'll try that. Sorry!

**Comment by TheKodeToad** [comment]
This feature is still missing though.

**Comment by TayouVR** [comment]
you can replace the minecraft jar, which is generally all you need. And if you need that .json file too, I suppose you can put it in the global launcher managed minecraft versions folder.

**Comment by catvin82** [comment]
Thanks, but where is the folder?
