### ISSUE TITLE
Download Java automatically

### ISSUE THREAD

**Issue by lynrayy** [PrismLauncher/PrismLauncher#734]
### Role

Player, new users of Prism

### Suggestion

Prism launcher should automatically install java for selected minecraft version

### Benefit

Prism launcher will be more user-friendly with this feature

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Some people are repelled by the fact that you have to manually install and set java in Prism (j1.8 or j17). Therefore, it will be great if the launcher acts as an official launcher, GDLauncher, CurseForge and other user-friendly launchers

**Comment by ghost** [comment]
This is already being done #285

**Comment by lynrayy** [comment]
Nope, it's not done

**Comment by ghost** [comment]
I mean it's being worked on

**Comment by lynrayy** [comment]
![image](https://user-images.githubusercontent.com/59417884/211681546-378d13e8-21a5-404b-8be2-543c4556a8c2.png)
The dude I just recommended this launcher to got a problem

**Comment by lynrayy** [comment]
> I mean it's being worked on

Ok

**Comment by DioEgizio** [comment]
> ![image](https://user-images.githubusercontent.com/59417884/211681546-378d13e8-21a5-404b-8be2-543c4556a8c2.png) The dude I just recommended this launcher to got a problem

It's not a problem, it literally says what you have to do :/

**Comment by lynrayy** [comment]
Why i should do something while all other launchers does this A-U-T-O-M-A-T-I-C-A-L-L-Y?

**Comment by TheKodeToad** [comment]
The simple answer is because it's not finished yet. It is being worked on by timoreo22.

**Comment by DioEgizio** [comment]
> all

*Looks at all MMC based launcher*

but yeah the comment above explains it lol

**Comment by lynrayy** [comment]
> The simple answer is because it's not finished yet. It is being worked on by timereo22.

Im already know it. 
https://github.com/PrismLauncher/PrismLauncher/issues/734#issuecomment-1378016162

**Comment by DioEgizio** [comment]
then why did you write that?

**Comment by lynrayy** [comment]
![image](https://user-images.githubusercontent.com/59417884/211821883-6329fad8-1bf7-4800-8451-a8917e3f9de3.png)
then why did YOU write that?
It's not even topic about problem, its suggestion topic for java auto download

**Comment by DioEgizio** [comment]
Because it's not "a problem" with prism

**Comment by TheKodeToad** [comment]
I don't think anyone thinks this is a bad idea (well, perhaps MultiMC did but I don't know) - it's simply not *fully* implemented yet. Nobody said you *should* have to do it manually.

**Comment by Scrumplex** [comment]
The simple answer to why this isn't a thing yet is, that the set of developers and the set of users having issues installing Java does not overlap mostly.

I just use my distribution's package manager to get my Java versions. You can do the same using WinGet on Windows. I would personally never use a JRE bundled by a launcher, if I could just use the one packaged by my distribution.
Though I am not opposed to this feature in any way.

If anyone wants to implement this, go ahead and we might merge it. Though it is quite complex, considering the way we do Java currently.

This feature request has been a thing ever since PolyMC was initially forked from MultiMC, which was over a year ago by now.

**Comment by TheKodeToad** [comment]
Even if you look at IntelliJ IDEA - which is made for Java developers - it has this feature. Eclipse and NetBeans don't though - although Eclipse bundles a default version similar to how Prism does (Prism unfortunately only on Flatpak).

**Comment by DioEgizio** [comment]
Yeah I think java downloading/management is a very important feature

**Comment by Minenash** [comment]
Unfortunately the lack of this feature is the main reason why none of my friends ended up sticking to any MMC based launcher. The first time I helped them install java, but (at the time) downloading for Windows wasn't the most user friendly thing, so if they ever got a new computer or reinstalled their os, they didn't want to deal with the hassle of installing Java to have the launcher even work, and especially once Minecraft started updating which Java it used causing them to have to install it again (and even just having the latest isn't enough, because old versions don't work with Java 9 or higher)

**Comment by TheAirBlow** [comment]
> Unfortunately the lack of this feature is the main reason why none of my friends ended up sticking to any MMC based launcher. The first time I helped them install java, but (at the time) downloading for Windows wasn't the most user friendly thing, so if they ever got a new computer or reinstalled their os, they didn't want to deal with the hassle of installing Java to have the launcher even work, and especially once Minecraft started updating which Java it used causing them to have to install it again (and even just having the latest isn't enough, because old versions don't work with Java 9 or higher)

Personally it would be worth it for me. It isn't hard to do in any way or capacity, and takes like 5 minutes, and you get the best modding UX afterwards... And it's not like you have to install a lot of versions, it is just 17, 11 and 8. If you don't play the version range that uses for example java 8 you can just skip it.

Although I do think java management is good in terms of UX, but please, dead god, **do it only for Windows**, Linux has package managers! 

~~Unpopular opinion: this is a barrier to keep zero effort Windows users from Prism. Also, do not eat me alive, this is an obvious joke!~~

**Comment by leumasme** [comment]
> The simple answer to why this isn't a thing yet is, that the set of developers and the set of users having issues installing Java does not overlap mostly. [...] You can do the same using WinGet on Windows.

I personally get my Java via Scoop on Windows. This works very well, but It's still not a clean experience with Prism Launcher because I still have to check which Java version is the correct one for the current Minecraft version whenever I create a new Instance.
