### ISSUE TITLE
Wrong / used for file pathing windows

### ISSUE THREAD

**Issue by asdfghjkl403622** [PrismLauncher/PrismLauncher#824]
### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.4.2

### Description of bug

when using $INST_MC_HOME to get the file path to a batch file to run, it uses backslashes (/) instead of forward slashes (\)

### Steps to reproduce

use $INST_MC_HOME in the pre-launch commands field on any instance in windows and check the logs

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TayouVR** [comment]
I think internally Qt handles either slash in paths generally, it will pretty much convert windows' back slashes `\` into regular unix forward slashes `/` to work on them. We could probably swap them out when printing them into logs, but I personally don't see much reason to do that.

Are the slashes causing issues somewhere?
As you can see in your own post backslashes have special properties, which is why generally people prefer to use forward slashes to avoid causing weird phenomenons

**Comment by asdfghjkl403622** [comment]
I want to run A windows batch file and give it the path to the minecraft instance, and I cannot due to there being no way to swap out the type of slash.

**Comment by asdfghjkl403622** [comment]
thanks! :D
