### ISSUE TITLE
Move API keys to GitHub Actions Secrets

### ISSUE THREAD

**Issue by Shijikori** [PrismLauncher/PrismLauncher#829]
### Role

Store and use the API keys safely

### Suggestion

Put the API keys and other sensitive information in a safe storage away from public eyes

### Benefit

It would keep Prism's API keys safer from revokation

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Currently, the API keys are in the CMakeLists.txt, meaning they are available for everyone to see and use.

I have used GitHub Actions myself to deploy a Discord bot on Google App Engine (the repo for that bot is currently private). I know of the Secrets which are specifically made for sensitive information, which I have used to keep my GCP Service Account used for the bot's deployment safe, in case I were to make the code repo public.

Looking up about CMake, I believe it would be possible to remove the API keys from the CMakeLists outright and pass them as arguments in the Actions with the value stored as a secret.

I think this would be preferable since the API keys are currently safe only if everyone acts in good faith towards the project.

**Comment by TheKodeToad** [comment]
It would make contribution harder. I wonder which keys (if any) could be revoked on their own though.

**Comment by Shijikori** [comment]
Are there significant frictions in obtaining API keys?

**Comment by TheKodeToad** [comment]
Obtaining an msa client id is quite confusing. It took me about a year to find out you could get it without entering your card details and billing info.

**Comment by DioEgizio** [comment]
we can do that but we won't because there's no advantage on doing this and it's gonna break building from source

Also the API keys don't need to get ""secured""

**Comment by Shijikori** [comment]
just out of curiosity, what do you mean by "the API keys don't need to get ""secured"" " ? Are they not considered sensitive?

**Comment by Scrumplex** [comment]
A large part of our user base relies on builds that do not originate from our GitHub Actions workflows, especially almost all of our Linux users.

Furthermore it is impossible to hide API keys for software that is running on *untrusted* systems. The keys need to be embedded into the final binary, and if someone wants to mess with us, they can just extract those keys. And once they are public, there is no reason to hide them anymore.

The API keys in question are not confidential in any way. The Microsoft client is just an identifier, not a secret. You are supposed to keep it public, as it will be transmitted in the authorization flow. You can also check our client id by checking [a very predictable url](https://prismlauncher.org/.well-known/microsoft-identity-association.json).

About CurseForge: We have received word that it's permitted to distribute the API key like this. It is also annoying to get new keys from CurseForge, which is why it's more convenient for everyone involved.

**Comment by Shijikori** [comment]
That makes it clear enough, thanks. Sorry for the bother

**Comment by Scrumplex** [comment]
I don't see any risk that our Microsoft client ID could get revoked. I don't know about CurseForge though, as they have been very vague regarding this topic.

**Comment by Shijikori** [comment]
Yeah, I am not too informed about that but I assumed CF was somewhat troublesome for MultiMC to drop them (they mention the ToS as a reason for dropping support, as far as I know).

**Comment by TheKodeToad** [comment]
> Furthermore it is impossible to hide API keys for software that is running on _untrusted_ systems. The keys need to be embedded into the final binary, and if someone wants to mess with us, they can just extract those keys. And once they are public, there is no reason to hide them anymore.

Key extraction happened with MultiMC and I'm suprised it was such a big deal.
