### ISSUE TITLE
Whole client crashes when installing a pack from ATLauncher

### ISSUE THREAD

**Issue by BorealBlizzard** [PrismLauncher/PrismLauncher#845]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.4.2

### Description of bug

When downloading the Yogscast Complete Pack through ATLauncher the whole programs crashes when at the extracting stage.

### Steps to reproduce

> Add Instance
> ATLaucher
Search "Yogs"
> Yogscast Complete Pack
> OK
> Select Recommended (Also crashed when only installing what was checked by defualt)
> Install
Wait For Crash

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
can you provide the `Prismlauncher-0.log` from the launcher data directory?
It will help in ensuring we are dealing with the same issue if we replicate it.

**Comment by ghost** [comment]
Can reproduce 
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/10713334/PrismLauncher-0.log)

**Comment by BorealBlizzard** [comment]
I dont think i have a file by that name, searched my whole filesystem for it. If it matters im using prismlauncher-bin from the AUR. Ill give the flatpack a try and see if it makes a log.

**Comment by BorealBlizzard** [comment]
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/10715173/PrismLauncher-0.log)

**Comment by Emily9121** [comment]
Same issue, with Windows 10 21H2 running Prism Launcher 6.3 and also tried with 5.2 without success.

[PrismLauncher-3.log](https://github.com/PrismLauncher/PrismLauncher/files/10793923/PrismLauncher-3.log)
[PrismLauncher-1.log](https://github.com/PrismLauncher/PrismLauncher/files/10793926/PrismLauncher-1.log)

**Comment by DioEgizio** [comment]
can reproduce

**Comment by Scrumplex** [comment]
This happens because of a race condition when loading component information. Specifically, if LiteLoader is used in a modpack.

If there is no locally cached metadata, the code will not wait for the load task to finish and will try to access version information right away.

Relevant code:

detecting LiteLoader here:
https://github.com/PrismLauncher/PrismLauncher/blob/09d607f39c47a467de5dde260e90771ad0ac51df/launcher/modplatform/atlauncher/ATLPackInstallTask.cpp#L503-L509

loading metadata here:
https://github.com/PrismLauncher/PrismLauncher/blob/09d607f39c47a467de5dde260e90771ad0ac51df/launcher/modplatform/atlauncher/ATLPackInstallTask.cpp#L1041-L1058

using metadata here: (source of segfault)
https://github.com/PrismLauncher/PrismLauncher/blob/09d607f39c47a467de5dde260e90771ad0ac51df/launcher/modplatform/atlauncher/ATLPackInstallTask.cpp#L606
