### ISSUE TITLE
Mangohud is not detected

### ISSUE THREAD

**Issue by Tokariew** [PrismLauncher/PrismLauncher#91]
### Operating System

Linux

### Version of PolyMC

1.4.2.gitfb4cf0b-1

### Version of Qt

Qt 6.3.1

### Description of bug

Mangohud option is being grayed out in the settings.
On PolyMC 1.4.2 worked fine, and was able to run with mangohud

### Steps to reproduce

1. go to settings
2. see greyed out option

### Suspected cause

Not sure if it's because of using copr version
https://copr.fedorainfracloud.org/coprs/g3tchoo/prismlauncher/packages/
Fedora 36
Mangohud is installed both for 32 and 64bit.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by getchoo** [comment]
can you try launching prism through the cli and post any errors that pop up?

**Comment by Tokariew** [comment]
don't see any error except of this 
```
➜ prismlauncher
    0.034 W Removing cache entry because of old age!
    0.165 W Removing cache entry because of old age!
    4.151 W STDERR "NOTE: Picked up JDK_JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true\n"
```

Isn't mangohud somehow not detected after this PR https://github.com/PolyMC/PolyMC/pull/1034

**Comment by Tokariew** [comment]
after removing PolyMC folder in `~/.local/share`
I get `fish: Job 1, 'prismlauncher' terminated by signal SIGSEGV (Address boundary error)`

and with `dmesg -wT` i get 
```
[Wed Oct 19 00:13:24 2022] traps: prismlauncher[8217] general protection fault ip:7fcc4c4825de sp:7ffc4adb6b18 error:0 in libQt6Core.so.6.3.1[7fcc4c435000+392000]
```

**Comment by getchoo** [comment]
hey sorry for the wait

it seems like there was an issue with the way i versioned the packages on copr - it's fixed now, along with the full release being added - so you may have been running a version with this bug that is not present in the release. could you upgrade the package and see if this still happens?

**Comment by Tokariew** [comment]
no longer being killed by `SIGSEGV` but mangohud option is still grayed out.
Gamemode is being detected but not mangohud
I checked Appimage and `PrismLauncher-Linux-Portable-5.0.tar.gz` version from release and both are not detecting mangohud for me. So it seems that it either something wonky with my linux setup or 
https://github.com/PolyMC/PolyMC/pull/1034 this PR not working correctly @Scrumplex

**Comment by Scrumplex** [comment]
AppImage won't be able to see MangoHud at all I think.

You might need to update your `LD_LIBRARY_PATH` variable if mangohud isn't installed at the its place.

**Comment by Tokariew** [comment]
ok after adding entries in the `/etc/ld.so.conf.d` and running `sudo ldconfig` it work fine.
Fedora by default didn't put the files there for mangohud
So not sure if detection based on `LD_LIBRARY_PATH` is ok.

**Comment by Scrumplex** [comment]
I would argue that this is a packaging issue on Fedora's end. It works fine on other distros from what I know

**Comment by lemonzest79** [comment]
I know this issue is closed but just wanted to say adding a conf file to /etc/ld.so.conf.d/ with the contents /usr/lib64/mangohud/ followed by sudo ldconfig made the mangohud available for the AppImage :)

**Comment by Jan200101** [comment]
> I would argue that this is a packaging issue on Fedora's end. It works fine on other distros from what I know

Absolutely not.
This is a supported configuration by the upstream project
https://github.com/flightlessmango/MangoHud/blob/ddbb4f5be1dba235ebfd770f622c5fe8be46987e/src/meson.build#L4

And this was present in the inital PR and removed with https://github.com/PolyMC/PolyMC/pull/1034

**Comment by getchoo** [comment]
yeah i would agree with that, especially since it's set to true by [default](https://github.com/flightlessmango/MangoHud/blob/ddbb4f5be1dba235ebfd770f622c5fe8be46987e/meson_options.txt#L5)

after looking around at some other distributions' packages, it seems like it's common to leave it as is too. i made a debian docker container to test this (since it's one of the aforementioned packages) and the same issue occurred
![image](https://user-images.githubusercontent.com/48872998/206585982-fbaeb376-aada-485d-ba57-2f0629990a2e.png)

since [ubuntu](https://packages.ubuntu.com/source/jammy/mangohud) uses the same [source](https://salsa.debian.org/games-team/mangohud/-/blob/debian/0.6.5-2/debian/rules) as debian, i'm guessing this issue will also occur there as well as on derivatives

the only packages from the distributions on the download page i've found to use this flag are the [gentoo (guru overlay) packages](https://gitweb.gentoo.org/repo/proj/guru.git/tree/games-util/mangohud/mangohud-0.6.8.ebuild#n81) and the [aur packages](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mangohud#n42). the aforementioned [debian/ubuntu](https://salsa.debian.org/games-team/mangohud/-/blob/debian/0.6.5-2/debian/rules#L9) package, [fedora](https://src.fedoraproject.org/rpms/mangohud/blob/6da66fb6c0290cb5df8c1529074f8e8c1537ca8c/f/mangohud.spec#_64), [nix](https://github.com/NixOS/nixpkgs/blob/7e49471316373c471a3bf4b78c130ebc907ae2d2/pkgs/tools/graphics/mangohud/default.nix#L131), [opensuse](https://build.opensuse.org/package/view_file/openSUSE:Factory/mangohud/mangohud.spec), and [void](https://github.com/void-linux/void-packages/blob/aa3cb7c49c29d64d53ca9ed5bd52e002cbf6397c/srcpkgs/MangoHud/template#L7) packages all do not, so it's possible this issue is present in those as well

**Comment by Splarkszter** [comment]
i had to build mangohud from source on ubuntu(LinuxMint) but i can't find a way to make it work on Prism/PolyMC

**Comment by Jan200101** [comment]
> 

How is it installed?
PrismLauncher looks for the implicit vulkan layer json that MangoHud ships
like
`/usr/share/vulkan/implicit_layer.d/MangoHud.json`

**Comment by ActuallyTheOwner** [comment]
Seems to be an issue on Debian Trixie
I have the flatpak for mangohud and used the install script from mangohud's github
