### ISSUE TITLE
Issues with Stack Smash failure on various mods?

### ISSUE THREAD

**Issue by FormBurden** [PrismLauncher/PrismLauncher#916]
### Operating System

Linux

### Version of Prism Launcher

6.3

### Version of Qt

6.4.2

### Description of bug

Lately I've been running into Java Stack Smashing errors that I guess goes to the LWJGL Dependency according to a 2/23/2023 Discord comment from the Luna Pixel Studios page for the Better-MC modpacks from Frontear M: 

> so technical explanation: LWJGL packages GLFW, but the version packaged in, 3.3.1 iirc, has a bug with that build of GLFW that causes a stack smashing error. The issue does NOT exist in 3.2.2, and from what I hear it also does not happen in the absolute newest GLFW (built from source) libraries either. The current solution is to either use an older version of LWJGL (3.2.2 where the issue doesnt happen), or to force LWJGL to use your source-built GLFW libraries (a bit more tedious since LWJGL is picky apparently). The newest builds of LWJGL may also be fine, I havent tested those though.

Since apparently LWJGL takes so long to update, everyone is using the 3.3.1 build for their Clients. My OS is Arch Linux and I use the AUR package, and obviously make all the dependencies with the AUR software itself and then delete. So when I searched the only place for LWJGL for Arch-Linux which is from the AUR store, and I didn't have it installed at all. 

Anyone know of this issue at all? And have run into it in their mod-order? Or possibly how to build Prism with 3.2.2 LWJGL (if you even can). 

### Steps to reproduce

Modpack obviously works, but adding other mods that don't even conflict with anything, the more you add, the more likely you will run into the Stack Smashing error.

This has happened for a few months now. On my Main Desktop, and same issue can happen on Steam Deck, which is installed from the flatpack for Prism.

### Suspected cause

Here is the log if it helps

[https://mclo.gs/P8yhZgg](https://mclo.gs/P8yhZgg)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kumquat-ir** [comment]
You can just change the LWJGL version from the instance's version page, select LWJGL 3 in the list and click "change version". Setting 3.2.2 as the default would likely have to happen in Prism's metadata server.

![Screenshot_2023-03-06_21-53-01](https://user-images.githubusercontent.com/66188216/223308256-c58bda05-8438-4705-96ea-e93c8b235454.png)

**Comment by Frontear** [comment]
LWJGL bug. Something in GLFW iirc which isnt fixed in the version LWJGL uses. Either use 3.2.2 as suggested, or build GLFW libs from source, and link/replace them into LWJGL (more complicated idek how to do it i just know it's possible)

**Comment by Frontear** [comment]
Oh wait, you referenced me. Haha missed that. As recommended above, you can switch versions in the modpack settings. Youll have to do it manually per modpack, but itll stay that way once changed

**Comment by FormBurden** [comment]
Oh wow, more simple than I thought. I'm surprised I never noticed that. Yet it's the first thing that comes up when you "edit" your mod pack. ;D 

I just tested it, and the mods that would crash no matter what, are now working! Nice.

**Comment by uforek** [comment]
I'm trying to run AOF6 and downgrading to LWJGL to 3.2.2 and 3.2.1 doesn't seem to avoid this bug.

**Comment by Yeshey** [comment]
Tried to install the All of Fabric 6 - AOF6 Modpack too, was getting the ** stack smashing detected ** error, but changing the LWJGL version to 3.2.2 fixed that, however, now it gives the following error:

```
...
[01:54:32] [Render thread/INFO]: Loaded default options for servers.dat
[01:54:32] [Render thread/INFO]: Loaded default options for extra-folder
[01:54:33] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[01:54:33] [Render thread/INFO]: Loaded client.properties
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fcf0501674b, pid=179622, tid=179623
#
# JRE version: OpenJDK Runtime Environment (17.0.5+8) (build 17.0.5+8-nixos)
# Java VM: OpenJDK 64-Bit Server VM (17.0.5+8-nixos, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# 
C  [libglfw.so+0x1674b]
#
# Core dump will be written. Default location: Core dumps may be processed with "/nix/store/dxjk0fcjd7ww8d20kha0i5rd02rksqd5-systemd-251.11/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/yeshey/.local/share/PolyMC/instances/All of Fabric 6 - AOF6/minecraft/core.179622)
#
# An error report file with more information is saved as:
# /home/yeshey/.local/share/PolyMC/instances/All of Fabric 6 - AOF6/minecraft/hs_err_pid179622.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

seems to be about the glfw library which seems to still be about this same problem from the OPs post

I tried rebuilding the prism launcher with a specific glfw version but couldn't get it to work, or just don't know what version of glfw we need. I'm at a loss

**Comment by Frontear** [comment]
Try downloading the latest version of GLFW, and telling Prism to use native libraries instead. It should link GLFW from your `/usr/include` automatically, and hopefully that fixes the issue.

**Comment by Trayshar** [comment]
Having the same issue, using LWJGL 3.2.2 results in the crash posted above. Setting the native library by ticking the "Use system installation of GLFW" doesn't seem to work since the version doesn't change in the log.

I can launch with default settings tho, it just takes a lot of trying; If it does manage to pass the LWJGL init it runs stable.
I'm using Temurin and Manjaro if that matters.

**Comment by Yeshey** [comment]
Can confirm that in my case (in nixOS) ticking the "Use system installation of GLFW" box made it work. Didn't even need to download the latest version of glfw, it seems to have detected it automatically from wherever it is installed (it's also not in `/usr/include` in my case bc nixOS is a special snowflake :v)

to recap, to make AOF6 work in linux I had to:
1. Edit the "All of Fabric 6 - AOF6" instance > Version > LWJGL 3 > Change Version to 3.2.2 (or lower)
2. In the main window > Settings > Minecraft > Tick "Use system installation of GLFW" box (and making sure to have downloaded the latest version of GLFW)

**Comment by cravl-dev** [comment]
### The Issues
For me (Linux Mint 21 Cinnamon w/ Temurin) it was a similar sequence to everyone else here:

- LWJGL 3.3.1 + built-in GLFW **->** `***stack smashing detected***` errors on most, but not all launches.
- Rolled back to LWJGL to 3.2.2 **->** `libglfw.so` crash same as Yeshey's.
- Installed the latest `libglfw3 libglfw3-dev` from the repos (v3.3.6) and ticked the `Use system installation of GLFW` box **->** seemed to be fixed for a dozen or so launches, but then got hit with the same `libglfw.so` crash again.
- There were also a couple `***buffer overflow detected***` errors somewhere in the sequence of events, don't remember exactly what combination triggered those.

### The Fix
Upon investigating the log, I noticed that it didn't seem to actually be loading the system GLFW at all, and after a bit of searching I found [this issue](#513) which confirms that the native library workarounds _don't work for 1.19_. What I did instead to _actually_ make it work is this:

1) Clone and [build the source for your system](https://www.glfw.org/docs/latest/compile.html) (paying attention to options like Wayland support if that's what you're running)[^1]. Here's a little script of what I did (after installing build requirements, obviously):
```
[[ -d "$HOME/Downloads” ]] && cd "$HOME/Downloads"
git clone https://github.com/glfw/glfw.git && cd glfw
cmake -S . -B build -D BUILD_SHARED_LIBS=ON -D GLFW_BUILD_EXAMPLES=OFF -D GLFW_BUILD_TESTS=OFF -D GLFW_BUILD_DOCS=OFF && cmake --build build
mkdir -p "$HOME/.local/lib/glfw" && cp build/src/libglfw* "$HOME/.local/lib/glfw/"
```
2) In PrismLauncher settings, add to your Java options: `-Dorg.lwjgl.glfw.libname="$HOME/.local/lib/glfw/libglfw.so"`
    - For the Flatpack version, you might have to use Flatseal to give PrismLauncher access to that path.
3) You can safely switch back to LWJGL 3.3.1 as well. (Some mods might even require it?) 👍 

[^1]: You might think you could use the system version from the repos rather than building, but I couldn't get it to work because, [as explained in the issue linked above](https://github.com/PrismLauncher/PrismLauncher/issues/513#issuecomment-1342820473), the GLFW in the repos is built off the tagged versions rather than the master branch, and thus is missing some needed codepaths. Apparently making the system use a GLFW package built off the master branch is "trivial" at least on platforms like Arch and NixOS, but they don't elaborate and I'm on Mint anyway so I just opted to build from source.

**Comment by Trayshar** [comment]
@BinaryBurgr's answer fixed the issue for me. Thank you for this detailed elaboration!

**Comment by Frontrider** [comment]
@BinaryBurgr thank you. 

Also, on Manjaro you can install the `glfw-git` package, the binary will be in `usr/lub/libglfw.so`.

**Comment by Scrumplex** [comment]
A new version of LWJGL released this month and in an effort to mitigate this issue, I have gone ahead and replaced the GLFW shipped by Mojang with the GLFW version provided by the latest LWJGL release (3.3.2).

From my own testing, it fixed the crashes outlined in this issue.

If this issue persists or a fix is needed for arm64 as well, feel free to comment below so I can reopen this.

**Comment by sw5ciprl** [comment]
Hello, it appears this change has since been reversed, as LWJGL now only downloads 3.3.1 from Microsoft's servers. Could this issue be reopened? @Scrumplex

**Comment by Scrumplex** [comment]
> Hello, it appears this change has since been reversed, as LWJGL now only downloads 3.3.1 from Microsoft's servers

Are you sure? Check the instance log to see what libraries are loaded by Prism. It should mention a `lwjgl-glfw-natives-linux-3.3.2-lwjgl.1.jar` which is the swapped file

**Comment by sw5ciprl** [comment]
> > Hello, it appears this change has since been reversed, as LWJGL now only downloads 3.3.1 from Microsoft's servers
> 
> Are you sure? Check the instance log to see what libraries are loaded by Prism. It should mention a `lwjgl-glfw-natives-linux-3.3.2-lwjgl.1.jar` which is the swapped file

The file `lwjgl-glfw-natives-linux-3.3.2-lwjgl.1.jar` isn't present in the component configuration, so I had to edit it to download 3.3.2  as a workaround.

**Comment by Scrumplex** [comment]
> > > Hello, it appears this change has since been reversed, as LWJGL now only downloads 3.3.1 from Microsoft's servers
> > 
> > 
> > Are you sure? Check the instance log to see what libraries are loaded by Prism. It should mention a `lwjgl-glfw-natives-linux-3.3.2-lwjgl.1.jar` which is the swapped file
> 
> The file `lwjgl-glfw-natives-linux-3.3.2-lwjgl.1.jar` isn't present in the component configuration, so I had to edit it to download 3.3.2 as a workaround.

What platform are you on? Are you using Prism Launcher with our meta server? (You can check this in Settings -> APIs)

**Comment by sw5ciprl** [comment]
Apologies, it was in fact 3.3.2. However, my stack smashing issue was still present, whereas my manual edit of component config worked.
